### ISSUE TITLE
LABELS !

### ISSUE THREAD

**Issue by moinsy** [openvenues/libpostal#103]
Hi Al,
       Firstly I need to ask, how are the labels trained? Because I see content landing up in CITY which is not actually CITY but LOCALITY (for Indian Addresses). If I need to add LOCALITY label , do we need to train this label for its appropriate content from OSM , or its already trained but just needs a label to be put in. 
     So for me I really need many labels like LOCALITY customised for my purpose, do i need to create a label then train for it? Also i did look in _address_parser.c_  , but saw many header files included which I was unable cope with. Can you give a bit detailed explanation ! :) 
    About LANDMARKS , does libpostal support this label to be created using keywords like near, opp, above, beside?

Thank you,

**Comment by thatdatabaseguy** [comment]
The administrative labels like city, city_district, etc. are mapped from [OSM](http://openstreetmap.org) admin_level tag to our labels. This field mapping is different for every country, so if you can give me a few examples of entities that are mislabeled, we might be able to change the field mappings for India if there's something missing.

I do not recommend retraining the parser on proprietary data sets unless you are familiar with NLP research and sequence models. It's not really designed to be a black box that can be fed any arbitrary address fields and learn to parse them.

There's a new parser being developed in the [parser-data](https://github.com/openvenues/libpostal/tree/parser-data) branch, which is very far ahead of master, and a lot of work has been done on place names, so it's probably worth waiting for that to be released. One aspect of the new parser that should help in India is that we also train on place names that are points in OSM rather than polygons. This helps to include a variety of place names that may not have official boundaries like neighborhoods, suburbs, "colonies" in places like Delhi or Chennai, etc. In OSM these are usually listed as either "place=suburb", "place=neighbourhood" or "place=locality", and it's not entirely consistent. The first two tags would map to "suburb" in libpostal, whereas place=locality maps to city, and in OSM is [supposed to be used](http://wiki.openstreetmap.org/wiki/Tag:place%3Dlocality) for unpopulated places. If mappers are using this tag differently in India, we can alias it to "suburb" instead of "city" for instance. In the new OSM training data apparatus, there's the ability to override per-country rules within smaller areas (like you could say "admin_level=10 maps to suburb only within Delhi") as well as allowing more granular overrides for specific node/way/relation IDs.

Landmarks are not supported currently. If common landmarks you're interested in are in OpenStreetMap and can be clearly distinguished from other entity types like venues, etc. (that was not true in my initial survey), then it may be possible. I've recently developed a method for reverse-geocoding to metro stations for cities like Tokyo, where there are typically no named streets and metro station is actually a semi-official address component. Something similar could be used for landmarks, but to do that we'd have to have a precise-enough definition of "what counts as a landmark?" OSM [does seem to have the notion of a "reference point"](http://wiki.openstreetmap.org/wiki/Named_spots_instead_of_street_names), but this is rarely used, and not in India. Representing landmarks in OSM is more of a conversation to be had with the OSM community, but if there is a clear way to do it, we can build a point index of them, reverse-geocode to them and add them to the global address data set. Generating phrases like "opp", "near", etc. is both easy and partially implemented in the new branch.

**Comment by moinsy** [comment]
Thanks for the input, explains things a lot

Also when i try parser_data getting errors in make

'
make  all-recursive
make[1]: Entering directory `/home/justdial/Documents/parser_data'
Making all in src
make[2]: Entering directory `/home/justdial/Documents/parser_data/src'
Making all in sparkey
make[3]: Entering directory `/home/justdial/Documents/parser_data/src/sparkey'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/justdial/Documents/parser_data/src/sparkey'
make[3]: Entering directory `/home/justdial/Documents/parser_data/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I.. -I/usr/local/include    -Wall -Wextra -Wno-unused-function -Wdeclaration-after-statement -Wformat -Werror=format-security -Winit-self -Wno-sign-compare -DLIBPOSTAL_DATA_DIR='"/home/justdial/Documents/parser_data/new/libpostal"' -g -mfpmath=sse -msse2 -DUSE_SSE -g -O2 -O2  -MT libpostal_la-trie_search.lo -MD -MP -MF .deps/libpostal_la-trie_search.Tpo -c -o libpostal_la-trie_search.lo `test -f 'trie_search.c' || echo './'`trie_search.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I.. -I/usr/local/include -Wall -Wextra -Wno-unused-function -Wdeclaration-after-statement -Wformat -Werror=format-security -Winit-self -Wno-sign-compare -DLIBPOSTAL_DATA_DIR=\"/home/justdial/Documents/parser_data/new/libpostal\" -g -mfpmath=sse -msse2 -DUSE_SSE -g -O2 -O2 -MT libpostal_la-trie_search.lo -MD -MP -MF .deps/libpostal_la-trie_search.Tpo -c trie_search.c  -fPIC -DPIC -o .libs/libpostal_la-trie_search.o
make[3]: *** [libpostal_la-trie_search.lo] Error 1
make[3]: Leaving directory `/home/justdial/Documents/lib/libpostal/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/justdial/Documents/lib/libpostal/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/justdial/Documents/lib/libpostal'
make: *** [all] Error 2'

**Comment by thatdatabaseguy** [comment]
Ah, parser-data is a development branch and may not always compile depending on what's checked in (though that looks like the sort of error that "make clean" would fix).

In any case what really matters is not the code changes in that branch but the trained model files, which are not public yet.

I mentioned that branch mostly as something to keep an eye on as it's where the bulk of the work is going on right now.

**Comment by moinsy** [comment]
Oops, so i cannot implement this.
Anything on when you might release this ?

**Comment by thatdatabaseguy** [comment]
Not sure yet, but sometime in the next couple of weeks.

**Comment by thatdatabaseguy** [comment]
@moinsy libpostal 1.0 has been released and does much better on Indian addresses, especially with place names.
