### ISSUE TITLE
Working with Address Component Flags in Address Expander

### ISSUE THREAD

**Issue by bytebutt** [openvenues/libpostal#110]
I've been playing around with the address expander today and had some questions about how the address component flags are working. I think I may be misunderstanding something and was hoping someone could set me straight.

For my purposes, due to the nature of my input, I know that the string I'm looking at contains only the street address (e.g. "123 Candy Cane Ct" with potential unit type and number). I also know that I only have US addresses. Information such as the state and ZIP code are not present.

Looking to cut down on the number of expansions I get, I tried setting the address components option. For the sake of example, I'm OR-ing `ADDRESS_HOUSE_NUMBER` and `ADDRESS_STREET` to get the option value. However, the resulting expansions contain results that I wouldn't expect:

```
>>> expand.expand_address("123 Candy Cane Ct", languages=["en"], address_components=expand.ADDRESS_HOUSE_NUMBER | expand.ADDRESS_STREET)
['123 candy cane ct', '123 candy cane court', '123 candy cane connecticut']
```

Why was a "Ct -> connecticut" expansion performed? I would think that such a replacement would only occur if I also provided the `ADDRESS_ADMIN1` flag. Additionally, if the address also contains a unit and number:

```
>>> expand.expand_address("123 Candy Cane Ct Apt Ten", languages=["en"], address_components=expand.ADDRESS_HOUSE_NUMBER | expand.ADDRESS_STREET)
['123 candy cane ct apartment 10', '123 candy cane court apartment 10', '123 candy cane connecticut apartment 10']
```

The "Apt Ten -> apartment 10" expansion is applied even though I did not supply the `ADDRESS_UNIT` flag. The unit conversion still occurs even if I remove `ADDRESS_HOUSE_NUMBER`.

Any clarity on this matter is greatly appreciated. I'm sure I'm just misunderstanding something.

**Comment by thatdatabaseguy** [comment]
CT -> Connecticut is perfectly valid in street names such as state highways (counterexample: [CT Route 8](https://en.wikipedia.org/wiki/Connecticut_Route_8)).

Generally the mapping of dictionaries to component options can be found here: https://github.com/openvenues/libpostal/blob/master/src/gazetteer_data.c.

Ten -> 10 is part of numeric expression parsing, so that will happen anyway.

Applying unit dictionary expansions for the ADDRESS_STREET option is mostly because people (including me) sometimes stuff unit numbers into other fields on online forms, etc. Expansion was written before the parser, might be able to make the expansions more granular now, though the current parser is not trained on unit numbers and will usually label them as part of the street or house number. Incidentally, there's a new version of the parser being developed in [parser-data](https://github.com/openvenues/libpostal/tree/parser-data) which can parse unit and other sub-building information in many languages. When that release is ready and units, we can more readily assume the input is clean, or that the caller had an opportunity to clean it first.

There are a few misconceptions out there about expand_address, which I'll summarize again here: many developers think expand_address is supposed to give one result or a ranked list, and that's not what it's designed to do (someday perhaps). It's best to think of the results of expand_address as a set (not every language has this concept, but Python certainly does). When ```len(set(expand_address(a1)) & set(expand_address(a2))) > 0```, the two addresses are dupes. That comparison doesn't have to be done in memory, could be in ElasticSearch or a relational database or an on-disk DB instead, but the principle's the same. For that type of set operation, it doesn't really matter if there's one or two nonsensical expansions in the set (those won't occur in natural text), as long as the correct value that other humans would actually type _is_ in the set.

**Comment by bytebutt** [comment]
Thanks for the response. The info in `gazetteer_data.c` is exactly what I was looking for in terms of clarification. Multiple expansions are fine for my purposes, I was just trying to cull them as an optimization.
