### ISSUE TITLE
Removal of accent removal / accented letter conversion from latin scripts

### ISSUE THREAD

**Issue by jheimone1** [openvenues/libpostal#111]
At the moment it is not possible to use libpostal to clean addresses in a lot of European languages, as it automatically converts all accented letters to either their unaccented counterparts or into a combination of non-accented ascii letters (example: ä -> a or ä->ae). To my knowledge, it is somewhat allowed to do the latter transformation in German language (Jürgen -> Juergen), but it is an absolute no-no in any human-facing text for example in the Scandinavian languages and French, or my native Finnish. (Example: Pitkämäentie <> Pitkaemaeentie). Also, most free or commercially available geocoding services do not understand this translitteration and thus they won't find anything based on the street name.

It seems the transliteration is buried very deep in the code, perhaps also in the NLP training and there is no option to switch it off at present. 

Would it be a big effort to 1) make the transliteration optional or 2) (better) remove it completely and retrain the entire dataset using the proper accents?

**Comment by thatdatabaseguy** [comment]
As it turns out, you're in luck.

In the [parser-data](https://github.com/openvenues/libpostal/tree/parser-data) branch of libpostal, the branch I'm primarily developing in at the moment, I've made umlaut transliteration language-specific in expand_address (normalizations like ü => ue only happen if the detected/specified language is German), and added a new transliterator called ["latin-ascii-simple"](https://github.com/openvenues/libpostal/commit/58851a9088185c82d51efb0a2bfb1128d115c21f) which only transliterates punctuation, various types of hyphens, HTML entities, etc.

This approach will allow the parser to make only minimal modifications/sanitizations to the input string, possibly without even needing to lowercase the string used in the output.

Transliteration isn't buried very deep. It's a simple API, may even be able to be factored into its own library at some point. The tricky part is ensuring that the parser works just as well on e.g. Finnish text typed without accent characters (I'm aware that in many languages they're actually different letters of the alphabet, just referring to the Unicode designation) as with proper spelling. The current parser model is still trained on transliterated words, so it won't help to switch branches, but in the new model, the strategy will be to train on up to 3 different versions of every string: the original, correct local-language version (e.g. München), a version with Latin-ASCII transliteration (Muenchen, only for German, not any of the Scandinavian or Turkic languages), and a version with accents stripped (Munchen) so every spelling will at least be seen by the model and have a similar weight. The point of doing all of this is so that the model is robust enough to handle strings typed by non-native speaker (the "ignorant American spelling"), or by native speakers using a foreign keyboard, or for records from some database where the accents may have been stripped by an automated process, etc.

The new transliterators are not going to be in master for a little while, and the parser has to be fully retrained to take advantage of them, which takes about a full week end-to-end.

For people running their own geocoders, I usually suggest that strings be run through libpostal normalization at index time so the normalized strings returned from the parser can be found, but obviously that's not a possibility when using a third-party geocoder.

**Comment by jheimone1** [comment]
This is great news! I will definitely give it a try once the training data is available.

And I completely agree that it is a good idea to train the system both with accents and with accents stripped, as a lot of legacy data may have been entered in the 7bit ASCII times or may have been translitterated to that earlier.

**Comment by thatdatabaseguy** [comment]
Hey @jheimone1, libpostal 1.0 has been released into master, and no longer transliterates 

As mentioned, there's a new transliterator which only makes simple modifications to the input (HTML entity normalization, NFC unicode normalization). Latin-ASCII transliteration is no longer used at runtime. Instead, addresses are transliterated to multiple forms during training so the parser has to deal with all the variants rather than normalizing to a single variant (which previously was not even correct in cases like Finnish, Turkish, etc.) in both places.

In expand_address, there are also language-specific transliterators for German and the Scandinavian languages, which would not even apply in the case of Finnish.
