### ISSUE TITLE
Create Release/Version tag on an interval

### ISSUE THREAD

**Issue by johnlonganecker** [openvenues/libpostal#112]
Hey I was wonder if you guys could start using some sort of release version tags? I think it might make it easier for others to reference.

It could be something you guys do on a time interval once a month or once every 3 months etc or whenever you feel like doing it. Doesn't have to be anything formal.

I was thinking it would be helpful to have pre-built docker images on docker hub, but would be useful if I could attached it to a specific version instead of a git SHA hash.

**Comment by thatdatabaseguy** [comment]
Just one guy :-). Mapzen's a sponsor, but libpostal's otherwise an independent project.

I tagged a [v0.3](https://github.com/openvenues/libpostal/releases/tag/v0.3) release in May and just published a [v0.3.1](https://github.com/openvenues/libpostal/releases/tag/v0.3.1) incorporating a few changes in master since then.

There's a huge new release currently being worked on in the [parser-data](https://github.com/openvenues/libpostal/tree/parser-data) branch. I'll probably bump it up a major version to 1.0 since it adds some new tags and may take that chance to namespace the C APIs (/expand_address/libpostal_expand_address/)

Something that's a bit unique to libpostal is going to be versioning model files when it starts to retrain periodically (there may not be any code changes in a given month, so the "release" would just be an automated process pointing the data download script at the latest model files in S3).

**Comment by johnlonganecker** [comment]
For what it is worth I think it is a great project 👍. It was just my 2 cents. Keep up the good work!
