### ISSUE TITLE
Build without downloading data files

### ISSUE THREAD

**Issue by Soliah** [openvenues/libpostal#120]
Is there a way to build libpostal without downloading the data files as part of the build process? Or are they required during the compilation?

**Comment by thatdatabaseguy** [comment]
The files downloaded are the trained/learned models in serialized form. Technically the library can compile without them but they're definitely required at runtime, so to call any of the functions those files would have to be downloaded and in a known location (currently specified at ```configure``` time but could also be part of a runtime config).

Not sure if there's a precedent in Homebrew land. Usually with machine learning projects people release either code or trained models, whereas libpostal is both.

**Comment by dominikkukacka** [comment]
But how do we force it to not download the files? If I leave the --datadir out it will fallback to the default.

I solved it temporarily with not installing curl but that is not a real solution

**Comment by thatdatabaseguy** [comment]
The data files are required to use libpostal. If you've already downloaded the files, you can still pull and re-run ```make``` for code changes without having to download huge files every time. As long as there are no updates to the files, it won't download them again. But they need to be downloaded.

**Comment by Platzii** [comment]
I want to add this lib into a Docker container but I want to keep the image as small as possible. Adding the downloaded files increases the size of the image a lot. My solution would be to download the files on the host machine and mount them as a volume into the Docker container. (multiple containers will be running at the same time on the host)

So, an option to skip the downloads would be very, very handy. Without it, there will be a lot of waste of bandwidth and diskspace.

Please consider adding this feature!

**Comment by 13k** [comment]
👍 

Having that amount of data downloaded on every install blocks/hinders a lot of automated use cases, such as having builds on CI, docker or package managers, which should be able to cache/link/move that data.

**Comment by thatdatabaseguy** [comment]
Might be missing something, but is it not possible to just set --datadir to a directory on the shared mounted volume for all containers?

Concurrency is probably an issue, so when setting up the shared drive, can run:

```./src/libpostal_data download all $DIR_ON_SHARED_VOLUME```

That will store a few housekeeping files with the files' server timestamps to ensure that the same data files are not downloaded again.

Then in each container, run: ```./configure --datadir=$DIR_ON_SHARED_VOLUME```

As a general architecture point, there are few workloads short of FB/Google-scale that are likely to be able to exhaust a single libpostal process in terms of addresses per second (some ingestion workloads might benefit from partitioning). The primary reason to have multiple instances running is usually high availability rather than performance/throughput. And if high availability is the goal, it's better to have N distributed machines in different data centers (which can either be smaller, cheaper machines or single libpostal containers running on various machines that host various other types of containers) than to have N processes, each using 2G of RAM, on a large machine that's a single-point-of-failure.

**Comment by dominikkukacka** [comment]
White the `volumes` approach is valid, I do it a bit different.
I use libpostal with node_postal in a docker container, and it is a bit inconvenient  to download all the data every build. Also I don't want to work with volumes but put everything in docker containers for versioning.
What I now have is a container with libpostal data only, and one with library but without the data. I then mount the data-only container into the app container and run it.

So actually it would be better for me if the download was a separate task, because in the data-only container I really only need the data, without building any libraries.

**Comment by thatdatabaseguy** [comment]
@dominikkukacka what I'm suggesting is to mount the volume first, then install libpostal. The housekeeping files (last_updated*) will already be present on the mounted data dir and prevent ```make``` from downloading the same thing twice.

**Comment by dominikkukacka** [comment]
@thatdatabaseguy yes makes sense if I am building my images on the machine where I am running, but my images are built on a CI system outside of my infrastructure. so what I would have to do is tar the data output and move it over to my production systems. it would be much easier to just build two docker images one for data and one with the lib, so that I don't have to redownload all the data.

**Comment by Platzii** [comment]
We also build our images on a separate CI system.

Running multiple instances on 1 host is done because the app that is using libpostal is not performing enough to use the full capability of the host. Not because of the libpostal performance.

**Comment by thatdatabaseguy** [comment]
I suppose that's valid. In any case, ```./configure --disable-data-download``` is now available in master.

Note (for others reading this in the future): the data files are still not optional and need to be downloaded in order to use libpostal. This change simply allows for decoupling the build from the data files for CI use cases.

**Comment by dominikkukacka** [comment]
@thatdatabaseguy awesome! any chance to also get the exact oppposite? downloading without building the library? :D

**Comment by thatdatabaseguy** [comment]
That's the script mentioned above: ```./src/libpostal_data download all $DATA_DIR```

**Comment by dominikkukacka** [comment]
@thatdatabaseguy ah perfect, overlooked it. Thank you very much for the support and thank you very much for the awesome project. Merry Christmas!

**Comment by rinigus** [comment]
Thank you for adding this option! It allows now to simplify building packages and makes it easier to provide alternative datasets, such as the ones generated for a single country.
