### ISSUE TITLE
Parser seems to struggle with Japanese addresses

### ISSUE THREAD

**Issue by lukeholman** [openvenues/libpostal#123]
Hey all,

I've been using the parser to do academic addresses from all over the world, and mostly it works very well. However it seems to really struggle with Japanese address that should be easy enough, like these examples (done in R using the 'postal' library). I guess maybe Japanese cities are not programmed into the parser yet - and the country name "japan" is missing too? Funny because it has an impressive ability to recognise many smaller countries (e.g. St Lucia). 

Cheers!

```
> parse_addr("department of biological science, kyoto university, kyoto, 123452345, japan")
                                                    house house_number road suburb city_district  city state_district state postal_code country
1 department of biological science kyoto university kyoto         <NA> <NA>   <NA>          <NA> japan           <NA>  <NA>   123452345    <NA>
```

```
> parse_addr("osaka university, osaka, japan, 37211")
                         house house_number road suburb city_district city state_district state postal_code country
1 osaka university osaka japan         <NA> <NA>   <NA>          <NA> <NA>           <NA>  <NA>       37211    <NA>
```

**Comment by thatdatabaseguy** [comment]
See #62 and the [blog post](https://medium.com/@albarrentine/statistical-nlp-on-openstreetmap-b9d573e6cc86).

The original parser didn't include training data for all countries, particularly those using the East Asian address system (Japan, China, and South Korea) because the address formats in those countries vary depending on which language is being used. In Japanese an address is written from least specific (country) to most specific (house number or venue name), whereas in English it's written using Western conventions. This required some changes to the [address-formatting](https://github.com/OpenCageData/address-formatting) repo, which is used by libpostal. Those changes have since been made and will be incorporated into the next release. There's a new and improved parser being worked on in the [parser-data](https://github.com/openvenues/libpostal/tree/parser-data) branch which fixes a number of issues related to parsing place names around the world, adds new tags like unit and po_box, and trains on every country.

An early version of the new model that's backward-compatible with the code in master (which should do ok on the above examples) can be found at: https://libpostal.s3.amazonaws.com/mapzen_sample/parser_full.tar.gz, if you want to try it out. To use that (doesn't require switching branches or anything, it's the same model in master trained on new data), just unpack the contents of the tarball into $DATA_DIR/libpostal/address_parser where $DATA_DIR is whatever you passed in during configure, default is /usr/local/share.

University addresses may be difficult to get exactly correct, even for humans, because with strings like "Osaka University Osaka", there is some ambiguity (is the second Osaka a city or a campus location and thus part of the university name?) Note that the parser ignores commas, the same way it ignores casing, so as not to depend on the runtime inputs looking like the training data.

**Comment by thatdatabaseguy** [comment]
Hey @lukeholman, libpostal 1.0 has been released, and it's trained on millions of Japanese addresses in Kanji, Romaji, and English.

The postcodes above are not correct, but using the postcode format for Japan (7 digits, hyphen after the first three like "DDD-DDDD"), the new parser produces the following correct output:

```
> department of biological science, kyoto university, kyoto, 606-8502, japan

Result:

{
  "house": "department of biological science kyoto university",
  "city": "kyoto",
  "postcode": "606-8502",
  "country": "japan"
}

> osaka university, osaka, japan 565-0871

Result:

{
  "house": "osaka university",
  "city": "osaka",
  "country": "japan",
  "postcode": "565-0871"
}
```

So I'll close this one if there are no objections.

**Comment by lukeholman** [comment]
Thanks so much! Looks great. 

All the best!

**Comment by thatdatabaseguy** [comment]
No problem!
