### ISSUE TITLE
Strange behaviour with Baja-California, Mexico

### ISSUE THREAD

**Issue by mkaranta** [openvenues/libpostal#126]
I have been testing libpostal against parts of the address set from https://results.openaddresses.io/ and have encountered some strange edge cases. I have been creating the test addresses using the OpenCage address formatting repository (https://github.com/OpenCageData/address-formatting).

For addresses in Baja-California, Mexico, libpostal seems to correctly tokenize but always appends the state into the city.

Examples:

```
LÓPEZ MATEOS, 106, 21840, MEXICALI, baja-california, mx
[(u'lo\u0301pez mateos', u'road'),
 (u'106', u'house_number'),
 (u'21840', u'postcode'),
 (u'mexicali baja-california', u'city'),
 (u'mx', u'country')]
CAMPOS, 7, 22580, TIJUANA, baja-california, mx
[(u'campos', u'road'),
 (u'7', u'house_number'),
 (u'22580', u'postcode'),
 (u'tijuana baja-california', u'city'),
 (u'mx', u'country')]
CORAL, 2676, 22850, ENSENADA, baja-california, mx
[(u'coral', u'house'),
 (u'2676', u'house_number'),
 (u'22850', u'postcode'),
 (u'ensenada baja-california', u'city'),
 (u'mx', u'country')]
LORENZO DE ZOVELA, 1126, 22715, PLAYAS DE ROSARITO, baja-california, mx
[(u'lorenzo de zovela', u'road'),
 (u'1126', u'house_number'),
 (u'22715', u'postcode'),
 (u'playas de rosarito baja-california', u'city'),
 (u'mx', u'country')]
TURQUESA (GENERAL ÁLVARO OBREGÓN), 165, 21480, TECATE, baja-california, mx
[(u'turquesa general a\u0301lvaro obrego\u0301n', u'house'),
 (u'165', u'house_number'),
 (u'21480', u'postcode'),
 (u'tecate baja-california', u'city'),
 (u'mx', u'country')]
```

**Comment by mkaranta** [comment]
There is similar behaviour for: baja-california-sur, michoacán-de-ocampo, san-luis-potosí, sonora, tobasco, and veracruz-de-ignacio-de-la-llave. Although, removing the hyphens tends to improve the ability of libpostal to tokenize the state.

**Comment by thatdatabaseguy** [comment]
So firstly, this is parsing not tokenization. Tokenization is splitting a string into words, which is deterministic and can be done without machine learning. Parsing or sequence tagging is assigning a classification or label to each token, and in this case it's assigning the wrong label.

Secondly, saying this as a Spanish-speaker, states names in Mexico are generally written without a hyphen (OpenAddresses simply hyphenates them because spaces are awkward in Unix path names), and any real user input is about as unlikely to contain hyphens as in the US i.e. no one would really write "New-Jersey" or "North-Dakota"..

The case where hyphens are more of a concern is in some places like Carmel-by-the-Sea, CA where it can be written both ways while OSM only has one form listed. Another case is non-French speakers forgetting to hyphenate when searching for French places. The solution for that (available in the next release) is to randomly replace hyphens in admin components with spaces when building the training data and possibly to make the place name dictionaries, which help the runtime parser distinguish between admin components, hyphen-insensitive so "Carmel by the Sea" and "Carmel-by-the-Sea" can share parameters/weights in the model. It's possible that something similar can be done for the reverse case e.g. even if it's very uncommon to write "New-York-City", just hyphenate any multiword admin component a small fraction of the time.

The next release also incorporates the vast majority of the OpenAddresses corpus into libpostal's training data alongside OSM, which should improve performance on addresses that look more like the ones in OpenAddresses (and therefore more like what government agencies publish).

**Comment by mkaranta** [comment]
Thank you for the answer. 

I did misuse the term tokenization there. Address parsing terminology is new to me and I was relying on the terms loosely thrown around from my compiler building days.

With experience, I have found that the use/non-use of hyphens in addresses is fairly consistent within countries, less often so with languages.

In the past month I built a small address test corpus of well-formatted OSM addresses using [OpenCage's address formatting repo](https://github.com/OpenCageData/address-formatting). At only 500mb, I doubt it is 1% of what you use, but I will gladly test the progress on this issue. I'll also test the latest model from Pelias (just for fun): https://libpostal.s3.amazonaws.com/mapzen_sample/parser_full.tar.gz

**Comment by thatdatabaseguy** [comment]
Right on. Small update: the next version of the training data does hyphenate multiword names a small fraction of the time as mentioned, which should generally help.

**Comment by thatdatabaseguy** [comment]
Hey @mkaranta (going in FIFO order, I'll get back to the French postcodes issue tonight or tomorrow) - so I've added the hyphenations to 1.0 and it gets all of the above correct:

```
> LÓPEZ MATEOS, 106, 21840, MEXICALI, baja-california, mx

Result:

{
  "road": "lópez mateos",
  "house_number": "106",
  "postcode": "21840",
  "city": "mexicali",
  "state": "baja-california",
  "country": "mx"
}

> 
> CAMPOS, 7, 22580, TIJUANA, baja-california, mx

Result:

{
  "road": "campos",
  "house_number": "7",
  "postcode": "22580",
  "city": "tijuana",
  "state": "baja-california",
  "country": "mx"
}

> CORAL, 2676, 22850, ENSENADA, baja-california, mx

Result:

{
  "road": "coral",
  "house_number": "2676",
  "postcode": "22850",
  "city": "ensenada",
  "state": "baja-california",
  "country": "mx"
}

> LORENZO DE ZOVELA, 1126, 22715, PLAYAS DE ROSARITO, baja-california, mx

Result:

{
  "road": "lorenzo de zovela",
  "house_number": "1126",
  "postcode": "22715",
  "city": "playas de rosarito",
  "state": "baja-california",
  "country": "mx"
}

> TURQUESA (GENERAL ÁLVARO OBREGÓN), 165, 21480, TECATE, baja-california, mx

Result:

{
  "road": "turquesa general álvaro obregón",
  "house_number": "165",
  "postcode": "21480",
  "city": "tecate",
  "state": "baja-california",
  "country": "mx"
}
```

It's also trained on OpenAddresses so has probably seen all of these before :-). There's a new Mexico countrywide data set in OA as well that didn't make it into this release but will be used in the next training batch.
