### ISSUE TITLE
Linking failure if snappy is static

### ISSUE THREAD

**Issue by rinigus** [openvenues/libpostal#133]
When using static build of snappy, libpostal demo programs fail to link due to missing C++ libraries. The problem is not there if we use shared snappy library. Issue is simple and due to the fact that snappy is, in fact, C++ library. To overcome it, I suggest to use C++ as a linker.

**Comment by thatdatabaseguy** [comment]
Not entirely familiar with the architecture being used, but unclear what's wrong with building Snappy as a shared lib or what the errors are.

In general I'm not a huge fan of C++ and don't want to make it a requirement for this project. Snappy is an indirect dependency of libpostal because it's a dependency of [sparkey](https://github.com/spotify/sparkey) and in any case it will soon be dropped from libpostal when the geodb module is.

Snappy as shared library should be considered a requirement for the moment.

**Comment by rinigus** [comment]
OK, no problem. Ideally, I would prefer to build the programs using static libs when its clear that its gonna be only program on the device using that library. But you are right, there is reason to start introducing changes if they are not required anymore soon.

**Comment by rinigus** [comment]
Maybe we should close the issue then?

**Comment by thatdatabaseguy** [comment]
Understandable, will close.
