### ISSUE TITLE
My bug, your bug, or a "feature"?

### ISSUE THREAD

**Issue by linuzer** [openvenues/libpostal#140]
While working on the parser using the Postgresql [module](https://github.com/pramsey/pgsql-postal) I found another strange thing, and I'm not sure wether it's just my "bad" data, the pgsql-postal module or a real issue in libpostal:

Taking this address-string, the quotation marks obviously are causing troubles:
`"Югра" Октябрьский район Ханты-Мансийский автономный округ - Югра Уральский федеральный округ`

In Postgresql
`select postal_parse('"Югра" Октябрьский район Ханты-Мансийский автономный округ - Югра Уральский федеральный округ')`
I get this error:
```
ERROR:  invalid input syntax for type json
DETAIL:  Token "югра" is invalid.
CONTEXT:  JSON data, line 1: {"house":"" югра...
```

and on the command line using address_parser this result:
```
Result:
{
  "house": "\" югра \" октябрьский район ханты-мансийский",
  "state_district": "автономный округ югра уральский",
  "state": "федеральный округ"
}
```

**Comment by linuzer** [comment]
The same issue occurs when a backslash occurs in the data, e.h. in this example:
`Центральная улица 35\1, 35\2 Суземский район Брянская область Центральный федеральный округ`

```
ERROR:  invalid input syntax for type json
DETAIL:  Escape sequence "\ " is invalid.
CONTEXT:  JSON data, line 1: ...ральная улица","house_number":"35 \ ...
```
```
Result:

{
  "road": "центральная улица",
  "house_number": "35 \\ 1 35 \\ 2",
  "road": "суземский район",
  "state_district": "брянская область",
  "city": "центральный",
  "state_district": "федеральный",
  "state": "округ"
}
```

**Comment by thatdatabaseguy** [comment]
That's an issue with the Postgres binding, which treats strings coming from libpostal as valid JSON. That is true 99.9% of the time, except when there are certain characters like quotes, etc. Can either raise an issue there: https://github.com/pramsey/pgsql-postal or remove problematic characters from the input before parsing.

**Comment by linuzer** [comment]
OK, but shouldn't a function that returns JSON make sure that it always returns correct JSON, no matter how bad the input was?

**Comment by thatdatabaseguy** [comment]
No, because none of the libpostal functions actually return JSON. The data structures used under the hood are just arrays of strings which contain most of the original characters from the input. It's up to the caller/binding to marshall those strings into the desired data structure/output format.

The command-line client is a C program that calls the libpostal API and formats the output, making it easy to test the parser without needing to write/compile C. The results are formatted as pseudo-JSON (though keys can repeat) for readability, and we do [escape those strings](https://github.com/openvenues/libpostal/blob/master/src/json_encode.c) before displaying them. The Postgres binding would simply need to do a similar sort of escaping before attempting to parse the result as JSON.

**Comment by linuzer** [comment]
Ah, OK, thank you for the clarification!
