### ISSUE TITLE
What are the fields I can expect from libpostal

### ISSUE THREAD

**Issue by Jeffrey04** [openvenues/libpostal#141]
What are the field names I can expect from the output of libpostal?

**Comment by thatdatabaseguy** [comment]
It depends on which version of the parser you're using, and field names may change over time (they'll).

In the default master version:: {house, house_number, road, suburb, city_district, city, state_district, state, country, postcode}

In the [intermediate model](https://libpostal.s3.amazonaws.com/mapzen_sample/parser_full.tar.gz): {house, near, house_number, road, entrance, staircase, level, unit, po_box, suburb, city_district, city, state_district, island, state, country, postcode}

And in the upcoming release: {house, near, house_number, road, intersection, entrance, staircase, level, unit, po_box, suburb, city_district, city, state_district, island, state, country_region, country, world_region, postcode}

**Comment by thatdatabaseguy** [comment]
In general when working with libpostal it's ok to depend on/operate on specific field names (if the field names do change it will be considered a breaking change and a major version upgrade), but it's a good idea to stay flexible to the number of possible fields.

**Comment by Jeffrey04** [comment]
would be nice if this is documented somewhere, is it a reference to any existing standard? (e.g. http://wiki.openstreetmap.org/wiki/Key:addr )

**Comment by thatdatabaseguy** [comment]
The admin components come from [the address-formatting repo](https://github.com/OpenCageData/address-formatting), which are in turn inspired by the OSM field names.

The sub-building fields like "unit" and "level" were added mostly after a survey of patterns in many real-world example addresses around the world, though sub-building components often need to be generated randomly in the training addresses (OSM rarely includes sub-building information).

Will add some documentation for the new release.

**Comment by Jeffrey04** [comment]
Speaking of the address-formatting repo, it kinda reminds me of UPU's S42 standard #offtopic

**Comment by thatdatabaseguy** [comment]
Somewhat similar, though there are slightly different goals. For address-formatting, the idea is to display results from a geocoder in a localized way, whereas for UPU it's delivering mail (formats vary depending on if it's being sent internationally or within country, etc). Libpostal's needs are a bit more compatible with address-formatting, since we basically receive a bunch of address components from {OSM, OpenAddresses} and need to reconstruct some possible user input from those components.

UPU formats have definitely been one of the sources used to inform sub-building patterns, etc.

**Comment by thatdatabaseguy** [comment]
Parser fields for the default model are now documented in the README and will be updated for the new release.
