### ISSUE TITLE
library version information would be useful

### ISSUE THREAD

**Issue by bradh** [openvenues/libpostal#145]
When integrated into an application, it can often be useful to know what version of the "heavy lifting" libs are in use (for error reporting / logging on a remote system for example). You can get the compiled-to version from the config.h header, but that may not match the running-against version - being able to show both would be handy, and some languages aren't big on compiled headers in any case.

In the longer term, knowing what data files are in use would also be useful, but a basic libpostal_version() function seems like a start. Will send a PR.

**Comment by thatdatabaseguy** [comment]
There's probably a larger conversation about versioning.

AFAIK most C libraries do versioning in the following way:

1. version is #define'd in one of the public header files. Making it a function means replicating that function in all the bindings, where the preprocessor def would suffice.
2. The shared library itself is often versioned and bumped on any ABI change i.e. adding ```-version-info 0:3:2``` to LDFLAGS.

**Comment by bradh** [comment]
Most C libraries did do it that way, until they realised that doesn't solve the problem (exactly because of shared libraries).

You build on 0.3, and get that header include value `"0.3". Now you make a bug-fix release (no ABI change) or just add a new function, so existing clients do not need to be recompiled. What version is each service / machine running? 

There are multiple ways to do it. Representative are curl, dbus, glib. A search through /usr/include will probably give you many more. A complete design for versioning seemed like too much for a first PR though.

**Comment by thatdatabaseguy** [comment]
True re: curl, etc. though libpostal has slightly more modest deployment goals than a ubiquitous Linux utility like curl that needs to be distributed in package managers, etc. It's mostly designed to be used by higher-level languages, and I don't see as many examples of that pattern in libraries that are routinely installed and used by Python extensions, etc. Counterexamples that are closer in use-case to libpostal would be more like Google's Snappy or LevelDB i.e. more /usr/local/include libs than /usr/include libs.

The releases so far have been a bit haphazard, so it's not that this won't ever become a issue, it just hasn't particularly been a issue so far, so would prefer to think through versioning a bit first, especially for the merge of the parser-data branch (which will probably constitute a 1.0 and for which we might want to create separate .so versions).

**Comment by bradh** [comment]
I see the importance of the version information as more closely correlated with the importance of that tool (i.e. how much work the library is doing) rather than the ubiquity of the tool. I only picked those particular examples because you likely have them. A better example would be something like Ogg Vorbis or Theora. I also note that leveldb has this kind of API in the C bindings (albeit as a pair of integers, rather than a string - `extern int leveldb_major_version()` and equivalent for the minor version).

Is the concern about introducing API that might become legacy? It really doesn't seem like that much code to maintain, and it is a convenient way for users (including bindings) to expose useful information.

**Comment by thatdatabaseguy** [comment]
Would simply like to consider it some more. As you mentioned above, libpostal has fairly unique versioning requirements as it's both software and trained models. With the next release, we'll likely start training models on some regular basis, so models can automatically incorporate updates to OSM and OpenAddresses over time. When certain changes are made to the C code, the models would have to be retrained to reflect them. In turn, some models may depend on a certain version of the code (model version in that case should probably be written into the data files themselves). There can also potentially be updates that involve no changes to code whatsoever, only a model update, and there's the question of whether those deserve a software version bump or not. There can potentially be parser labels added by just changing the training data. For some people looking to format the parser output as SQL tables, etc. that might even constitute an API change and thus a major version upgrade. Many people have expressed interest in training custom parsers, which I've largely tried to steer them away from doing, but it will inevitably happen, so that needs to at least be possible. Those are a few things that jump out anyway.

Re: leveldb it seems to define the version in both the Makefile and the header, where it's hardcoded: https://github.com/google/leveldb/blob/3080a45b626f8ddb474bc5e860796a48b51b3cf0/include/leveldb/db.h#L16, which is a bit bizarre.

**Comment by bradh** [comment]
I think of models as data, but that newer data versions might have a minimum code version requirement (which could be a minor version increment in semantic versioning as long older models would still work with the new format too, or a major version if they don't).

Output formats adding labels within the same basic format (JSON) wouldn't be an API break, because there is no assurance that any particular address has any particular label in any case.

So versioning for models is orthogonal to the versioning for code.
