### ISSUE TITLE
address_parse fails on normalized input

### ISSUE THREAD

**Issue by rinigus** [openvenues/libpostal#150]
As a part of using libpostal in mobile application, I wrote a small geocoder. While testing it, I found that some addresses in Estonia are parsed wrong if the input is normalized before parsing. Here, the proper version of libpostal was used (not country-specific model), version in last updated was `Tue Dec 13 14:03:51 2016`.

Namely, the street name is frequently assigned to `house` and not to `road`. See below a log from address_parser:

```
  > karikalda põik 123, kaberneeme, eesti

Result:

{
  "road": "karikalda põik",
  "house_number": "123",
  "city": "kaberneeme",
  "country": "eesti"
}

> karikalda poik 123, kaberneeme, eesti

Result:

{
  "house": "karikalda poik",
  "house_number": "123",
  "city": "kaberneeme",
  "country": "eesti"
}
```

As you could see, the second example fails. I wonder, should I just train my country-based datasets (https://github.com/openvenues/libpostal/issues/132) with normalized input to get around this issue? Or is it a bug and there is some other known workaround? I would prefer to normalize input before parsing it since that would allow to use transliteration while query for Cyrillic names, for example.

**Comment by thatdatabaseguy** [comment]
In master, it's usually better to parse the input then normalize each component.

For the new release everything's being trained on [unnormalized, UTF-8 normalized, and Latin-ASCII transliterated input](https://github.com/openvenues/libpostal/blob/parser-data/src/address_parser_io.c#L30). Tested that address with one of the recently-trained parsers on my laptop, and it works fine both ways. Not sure about adding full transliterations from non-Latin scripts as there are often several different transliterations for the same string and in general automated transliteration isn't super-accurate in every script. It might be fine to allow it for a few scripts that transliterate well like Greek and Cyrllic or something, but wouldn't want to do it for vowel-optional scripts like Arabic or Hebrew.

In the new release there's a simpler transliterator called latin-ascii-simple which just does HTML escaping, mapping ndash to hyphen, etc. so the parser output is closer to what the user typed. Also in normalization á=>ae only happens in German, not in Scandinavian, Finnic, or Turkic languages.

Haven't tested this, so no promises, but it should be ok to normalize the input yourself, as the corpus reader takes care of retagging lines where, say a token like "½" gets normalized to "1/2", which is now three separate tokens. If it sees something like "1/2/house_number" that can be further tokenized and would otherwise be invalid, it will assign the same label to all the "sub" tokens. Could tack on the normalized lines as long as ```shuf``` is installed or the training examples are shuffled randomly a priori.

**Comment by rinigus** [comment]
Thank you for a fast reply! It looks to me as well that parsing first / normalizing each component later works better. Since I normalize each address component separately when getting data from OSM in normalized table used for looking up addresses, I still get the hit while parsing / normalizing order.

It seems that ä -> [ae, a] occurs for Estonian as well, not just German.

I guess that you could just close this issue, since I've got the recommendation and explanation for the current behavior. Thank you very much!

**Comment by thatdatabaseguy** [comment]
Ah ok, transliterators can apply by script and language in the new scheme, so will configure Estonian to use the German conventions.
