### ISSUE TITLE
How to install this library to xampp?

### ISSUE THREAD

**Issue by imsocb** [openvenues/libpostal#157]
Hi, rather new to this library and php read the installation guide but did not find any relevant information on whether I can install this library onto window based xampp, before I  install the php binding? 

But before, I proceed with the installation can this library identify and extract any address from a string of text input? This library seems to be able to do that? Thanks for any help rendered.

**Comment by thatdatabaseguy** [comment]
The answer to both questions is no, unfortunately. We support Mac and Linux - Windows is not a priority but happy to accept patches.

The second question seems to be about address extraction, which was covered in [this issue](https://github.com/openvenues/libpostal/issues/22). Libpostal can parse string addresses and other geocoder input (the kind of text people type into Google Maps and similar products) into components like house_number, road, city, etc. in many languages (please see the [README]() for examples). Extracting addresses out of text (pulling the address out of free text like "We are located at 123 Main St") is not currently a solved problem, mostly because deriving a suitably large training corpus the way libpostal does with OpenStreetMap is considerably more difficult for general address extraction.
