### ISSUE TITLE
Weird parsing behaviour for Austrian address

### ISSUE THREAD

**Issue by dominikkukacka** [openvenues/libpostal#159]
I found a weird behaviour for "Eduard-Sueß-Gasse"
(Double name Eduard-Sueß plus Gasse for Street)

```
input: Eduard Sueß Gasse
house: eduard
road: suess gasse
house_number: 9

input: Eduard-Sueß Gasse
house: eduard-suess
road: gasse
house_number: 9

(this is right)
input: Eduard-Sueß-Gasse
road: eduard-suess-gasse
house_number: 9

input: Eduard Sueß-Gasse
house: eduard suess-gasse
house_number: 9
```

**Comment by thatdatabaseguy** [comment]
Road vs. house is one of the most common error classes for libpostal, so not entirely weird. It's a decently hard problem in some cases if you think about getting the boundary right between a venue name and the street it's on in places like Austria where street comes before house number. Where does the road begin? Eduard could be the name of a bar or restaurant or part of a doctor's name.

Can't make promises on this one, but an initial guess would be that Austrian streets, at least in every data set I've seen [are typically hyphenated](http://www.openstreetmap.org/way/5000227) and that's what libpostal trains on. As mentioned in the blog post, one instance where libpostal's ~99% accuracy doesn't always capture the real world is when the addresses used for testing are pathologically unlike the training addresses from OSM. Hyphenation differences are probably one of those cases. Libpostal works on tokenized strings and makes one prediction per token using attributes of the word, its surrounding context words and the model's own previous predictions. 

Hyphenating/de-hyphenating creates a different sequence of words as far as libpostal is concerned. In the fully hyphenated version of that string, it only has to make predictions for 2 words, one of which it's seen before since that street name occurs in OSM. If "Eduard" is not hyphenated, the parser would be using what it has learned from seeing "Eduard" on its own wherever that occurs (probably in venue names). It's also possible that the parser has never seen "Sueß" on its own, although when combined as "Sueß-Gasse", "Gasse" is a known street suffix and probably contributes more to the "road" weight than whatever word it's attached to. In any case, I can see where it would get some of those wrong even though for us all those forms look basically the same. Concatenation and hyphenation are often problematic when applying NLP models that rely on discrete tokens to Germanic languages. In the new release libpostal starts to handle the concatenation piece better by using character n-grams for unknown words, which appears to improve accuracy.

For hyphenation the way to "fix" it is probably to de-hyphenate streets as part of the training process i.e. when reading in the examples, if a hyphenated word like "Eduard-Sueß-Gasse" occurs, it could create 4 different training examples, or choose one at random for speed.

The main question I have is: is this something that's reasonably common in your data set/user input or are you more testing to look for edge cases? It's fine to do the latter and it's generally a good idea to characterize any machine learning system in terms of both aggregate statistics as well as its edge cases. I just want to understand the scope.

**Comment by dominikkukacka** [comment]
I assumed this would be a not so easy problem to solve.
In Austria I have seen many streets which contain double names but nobody could tell me what the official writing style was. The signs (sometimes on the same road) tell me different versions and also Openstreet maps and Google maps tell me something else.

So I am not sure if it would be reasonably to try it out with de-hyphenate streets as part of the training .

**Comment by linuzer** [comment]
> Road vs. house is one of the most common error classes for libpostal

Would it be an option to implement a parameter to disable the recognition/consideration of the house (not the number) completely? Because also in my scenario in Russia that is one of the main source of wrong results. And I think there are a lot of use cases that do not need at all the ability to find places by name (bars, restaurants, etc.). Of course a geocoder on a website needs that ability and therefore I understand that libpostal needs to deal with it. But at the other side there are use cases (my one for example: I have to geocode exclusively postal addresses), where I would prefer to disable this feature completely in order to increase the recognizing quality on all other addresses.

...just an idea... don't know if it's possible at all...

**Comment by thatdatabaseguy** [comment]
@dominikkukacka that proposal is relatively easy to implement and I can try it, just not sure if it will solve that specific test case or not (probably others like it though). I remember Austria having some strange addressing cases, particularly large apartment blocks in Vienna.

**Comment by thatdatabaseguy** [comment]
@linuzer that might be possible. I'd prefer not to train separate models for it, but the tags can probably be restricted at configure or runtime (that means there wouldn't be any size reduction because the model is effectively still keeping all its parameters, just ignoring predictions that aren't in a fixed set).

**Comment by linuzer** [comment]
That sounds perfect. So in other words the system would throw away results with a "house"-tag and only return the next likely match without. So when the decision is close between road and house, it would opt for the road (when the parameter is set).

**Comment by thatdatabaseguy** [comment]
@dominikkukacka libpostal 1.0 successfully handles all of these cases, and should be able to do something similar for others like them:

```
> Eduard-Sueß-Gasse

Result:

{
  "road": "eduard-sueß-gasse"
}

> Eduard-Sueß Gasse

Result:

{
  "road": "eduard-sueß gasse"
}

> Eduard Sueß-Gasse

Result:

{
  "road": "eduard sueß-gasse"
}

> Eduard Sueß Gasse

Result:

{
  "road": "eduard sueß gasse"
}
```

We de-hyphenate at random in the training data, and also add both n-grams of unknown words and sub-words in hyphenated phrases that weren't seen at training time (should help with Germany and Austria in particular).

**Comment by thatdatabaseguy** [comment]
@linuzer the new model shouldn't make as many road vs. house mistakes, so might not be necessary to implement the custom fields.

Closing the hyphenation issue.
