### ISSUE TITLE
'oude westen' incorrectly classified as a street

### ISSUE THREAD

**Issue by missinglink** [openvenues/libpostal#162]
hey @thatdatabaseguy, we had this issue reported over in [Pelias land](https://github.com/pelias/api/issues/795).

```
> Oude Westen, Rotterdam

Result:

{
  "road": "oude westen",
  "city": "rotterdam"
}
```

expected: 'neighbourhood' https://whosonfirst.mapzen.com/spelunker/id/85859807/#15/51.9209/4.4662
actual: 'oude westen' incorrectly classified as a 'road'

**Comment by thatdatabaseguy** [comment]
Hm, that particular neighborhood wan't getting used by libpostal's neighborhoods index. When constructing the training ("ingestion"), neighborhoods are added in the following way:

1. Get a lat/lon from an address or other point
2. Reverse geocode it to both the admin boundaries (OSM-only) and the neighborhoods index
3. The neighborhoods index includes several types of geographies in priority order:
    1. OSM data matched with [ClickThatHood](https://github.com/codeforamerica/click_that_hood) polygons
    2. OSM data matched with Quattroshapes polygons
    3. Unmatched ClickThatHood polygons
    4. Unmatched Quattroshapes polygons
4. Take the highest priority boundary that this point matches, and add it as "suburb" some random portion of the time.

Because Rotterdam [is covered by ClickThatHood](https://github.com/codeforamerica/click_that_hood/blob/master/public/data/rotterdam.geojson), those polygons override the Quattroshapes geometries. However, looking at the data I think the Rotterdam polygons are boroughs/city districts rather than neighborhoods. Most of the CTH files specify "neighborhoodNoun" if the boundaries are something other than neighborhoods, and otherwise AFAIK it was safe to assume they were neighborhoods, but that assumption seems to be unreliable outside the US.

Was originally planning to postpone this until after the release, but after [auditing/whitelisting the ClickThatHood neighborhoods](https://github.com/openvenues/libpostal/commit/6c68d446a05cd312f9a4cc4e2950fe45fef5cdf8) and trying to build a new index, my research server ran out of memory and crashed, so built the new index and restarted ingestion, which means this will in fact be fixed in the 1.0 release. See ya in 12 days...

The new index also includes neighborhood geometries from OSM itself where available (incidentally [Oude Westen is in OSM](https://www.openstreetmap.org/way/427502348)) and will occasionally select a matched neighborhood at random rather than the top result, which should ensure that virtually all the neighborhoods in the index have some representation in the training data.

**Comment by missinglink** [comment]
cool thanks @thatdatabaseguy 

by-the-way I made this thing you might like: https://github.com/missinglink/osm-boundaries

**Comment by thatdatabaseguy** [comment]
1.0 get this and other affected neighborhoods correct:

```
> Oude Westen, Rotterdam

Result:

{
  "suburb": "oude westen",
  "city": "rotterdam"
}
```
