### ISSUE TITLE
How to add address formats and enhance behaviors?

### ISSUE THREAD

**Issue by brianmacy** [openvenues/libpostal#169]
Overall libpostal is fantastic.  I've noticed cases where I'd like to improve libpostal behavior but am uncertain if there is a good way to do so.  A few things...

1. Singapore is a city/state so country, city, and state should all be Singapore.  This might help parsing too since Singapore should be the only option for those labels so the parser should know other words don't belong there.
 a) Postal codes should always be 6 digits.  Frequently, other information ends up also being labeled as a postal code.. building numbers, house numbers in the "###, house, road, city postal" format
 b) Also, there is a block format and building numbers that often get misparsed
2. I've noticed that the parser has a strong affinity to Road as a street type but court/ct, grove, park, etc often end up misparsed.

**Comment by thatdatabaseguy** [comment]
Needs some clarification. Do you mean queries like "Singapore, Singapore, Singapore"? AFAIK OSM only has Singapore as a [country](https://www.openstreetmap.org/relation/536780) and a [city](https://www.openstreetmap.org/node/531668011), so if that's incorrect it can be added in OSM and picked up on the next run.

It's easier to work with specific examples of incorrect parses if possible (input string, what the parser returned, and what you expected).

In general, there's a huge rewrite happening in [parser-data](https://github.com/openvenues/libpostal/tree/parser-data) that includes more data (includes most of [OpenAddresses](https://github.com/openaddresses/openaddresses), every street in OSM even if there are no addresses on it, a simple city/place name data set for cities represented as points rather than polygons, and a data set with all the postcodes in GeoPlanet and their containing admins), improvements to the features libpostal extracts from text for the machine learning model, and recently a substantially better model, specifically a Conditional Random Field, which finds a globally optimal sequence instead of making N local decisions, and can revise its previous decisions if that would help a subsequent token score higher (similar to the Viterbi algorithm in Hidden Markov Models but more powerful because it can use non-local state, and I've also added the notion of combined state+transition features which help the parser deal with the many formats/languages in the training data).

As far as sub-building information, for the new training sets I've created a new set of configs (here's an [English example](https://github.com/openvenues/libpostal/blob/parser-data/resources/addresses/en.yaml)) which allow for additions to be made to the OSM data to handle certain patterns like unit numbers i.e. if OSM has "123 Main St", we can simply sample a phrase from the libpostal dictionaries, pick a random number, and generate "123 Main St Apt #456".

So far there are several new labels for unit, level, po_box, entrance, and staircase. I debated adding tags for building and block as well, but there are a number of edge cases to consider (for instance in the address system of Brasilia, the capital of Brazil, "Bloco E" would actually be the house number), so it would just need some research. A building tag would also be a bit complicated because sometimes it's used as a unit (Australia, sometimes in the US), and sometimes as part of a larger sub-building context (Malaysia, China, Singapore), and we don't want the parser to get confused by having to predict two different responses based on something arbitrary about the training data. There's also a difference between numbered/lettered buildings and named buildings like we might see in the UK, so for existing named buildings, libpostal would need a system for distinguishing between when the building should be labeled as the "house" tag (venue or named building). and when it should use the "building" tag, again trying not to create arbitrary ambiguities.

Chances are the upcoming release will resolve most of these issues, and many of the annoying/obvious errors the current parser makes. The final version is training as I write this, hope to have it published next week or the following.

**Comment by brianmacy** [comment]
Thanks for the reply.  I’m working on getting approval to provide some real test examples.


On Mar 12, 2017, 12:18 PM -0400, Al Barrentine <notifications@github.com>, wrote:

Needs some clarification. Do you mean queries like "Singapore, Singapore, Singapore"? AFAIK OSM only has Singapore as a country<https://www.openstreetmap.org/relation/536780> and a city<https://www.openstreetmap.org/node/531668011>, so if that's incorrect it can be added in OSM and picked up on the next run.

It's easier to work with specific examples of incorrect parses if possible (input string, what the parser returned, and what you expected).

In general, there's a huge rewrite happening in parser-data<https://github.com/openvenues/libpostal/tree/parser-data> that includes more data (includes most of OpenAddresses<https://github.com/openaddresses/openaddresses>, every street in OSM even if there are no addresses on it, a simple city/place name data set for cities represented as points rather than polygons, and a data set with all the postcodes in GeoPlanet and their containing admins), improvements to the features libpostal extracts from text for the machine learning model, and recently a substantially better model, specifically a Conditional Random Field, which finds a globally optimal sequence instead of making N local decisions, and can revise its previous decisions if that would help a subsequent token score higher (similar to the Viterbi algorithm in Hidden Markov Models but more powerful because it can use non-local state, and I've also added the notion of combined state+transition features which help the parser deal with the many formats/languages in the training data).

As far as sub-building information, for the new training sets I've created a new set of configs (here's an English example<https://github.com/openvenues/libpostal/blob/parser-data/resources/addresses/en.yaml>) which allow for additions to be made to the OSM data to handle certain patterns like unit numbers i.e. if OSM has "123 Main St", we can simply sample a phrase from the libpostal dictionaries, pick a random number, and generate "123 Main St Apt #456".

So far there are several new labels for unit, level, po_box, entrance, and staircase. I debated adding tags for building and block as well, but there are a number of edge cases to consider (for instance in the address system of Brasilia, the capital of Brazil, "Bloco E" would actually be the house number), so it would just need some research. A building tag would also be a bit complicated because sometimes it's used as a unit (Australia, sometimes in the US), and sometimes as part of a larger sub-building context (Malaysia, China, Singapore), and we don't want the parser to get confused by having to predict two different responses based on something arbitrary about the training data. There's also a difference between numbered/lettered buildings and named buildings like we might see in the UK, so for existing named buildings, libpostal would need a system for distinguishing between when the building should be labeled as the "house" tag (venue or named building). and when it should use the "building" tag, again trying not to create arbitrary ambiguities.

Chances are the upcoming release will resolve most of these issues, and many of the annoying/obvious errors the current parser makes. The final version is training as I write this, hope to have it published next week or the following.

**Comment by brianmacy** [comment]
I’m eager to test the new parser.  If you have a test version you want someone to look at please let me know.  Any projections as to an ETA?

Here are some addresses that I’ve found problematic.  For my purposes, consistency is paramount to correctness.

1. First includes bldg-unit with road, second pulls out as unit
2 Adam Road 01-11, Singapore, 289876, Singapore
Adam Road Food Centre, 2 Adam Road, #01-11, Singapore 289876

2. The second has the bldg-unit as the house_number and unit as ‘#’.  Part of the house in the second “Kim Keat” is parsed out as an additional road while the rest ends up in house.  In the first address, Singapore ends up as two country fields (I’ve noticed when there is a postal in between we get country, postal,country but when there is no postal we get city, country)
Block 22 Lorong 7, Toa Payoh, Singapore, 310022, Singapore
#01-25, Kim Keat Palm Market and Food Centre, Blk 22 Lorong 7, Toa Payoh, 310022

3. The first parses perfectly.  The second has ‘#’ as unit, the bldg-unit as house_number, and 521A as part of the road.
531A Upper Cross Street, Singapore, Singapore
Hong Lim Food Centre, #02-43, 531A Upper Cross Street, Singapore 051531 Singapore

4. Don’t think I can blame lib postal for this second one. "Mararikulam Aleppey” ends up as part of the road but Mararikulam is the city and Alappuzha is the road.  Just wanted to include the example though.
Thayil Junction, Mararikulam, 688522, India
Thayyil Stop, Near Marari Beach Resort, Mararikulam, Aleppey, Alappuzha, 688522, India

5. City should be Raison (not road or house), kullu is the district (not city),
NH - 21, Camping Site Raison, Kullu, 175128 , India
NH-21, Raison, 175128, India

6. Swaps road/district between the two with Diplomatic Enclave and Chanakyapuri.  In reality, both are districts.
Diplomatic Enclave, 50-B Chanakayapuri, New Delhi, 110021, India
50-B, Diplomatic Enclave, Chanakyapuri,,New Delhi - 110021,India,IN

7. Unit B-127 ends up as part of road
4223 GLENCOE AVE. - B-127, VENICE, CA 90291 USA

8. Doesn’t pick out a road at all, puts Brooks into the City with Venice.
15 B BROOKS, VENICE, CA 90291 USA

**Comment by thatdatabaseguy** [comment]
Ok, the new parser is probably not going to perform very well on most of these cases. They're relatively edge case-y and while addresses are full of edge cases i.e. we don't want to necessarily ignore them, remember that libpostal is 98.9% accurate (new model looks like it will be above that when it's finished training), not 100%. If you have a hundred million addresses, that's a million mistakes, and using libpostal means tolerating some errors. The point is, while certainly not perfect, libpostal's hopefully better than whatever hacky regex solutions people were using before.

With that said, here's the case-by-case:

1. With units, we have to essentially generate the data randomly, since units are rarely included in OSM. The way this works is: we select a phrase randomly from the libpostal dictionaries (Apartment, Apt, #, No., etc.), generate a random number of a certain base-10 digit length, and optionally a letter to attach to it. We currently don't generate unit numbers with hyphens in them, so that's probably why it doesn't handle those cases well (it's more common for the parser to see a house number with a hyphen in it e.g. Canada, Japan, etc.)

2. For Singapore, the format we trained on was postcode before city, which looks a mistake in the  [address-formatting](https://github.com/OpenCageData/address-formatting) repo. I've submitted a [PR](https://github.com/OpenCageData/address-formatting/pull/36) to to correct that for the next time the training data are built, but unfortunately that change will not make it into the new release.

3. The new model trained on 10% of the data gets this reasonably correct, although it combines the unit and the house number (again might be because of the hyphenation):

```
> Hong Lim Food Centre, #2-43, 531A Upper Cross Street, Singapore 051531 Singapore

Result:

{
  "house": "hong lim food centre",
  "house_number": "#2-43 531a",
  "road": "upper cross street",
  "city": "singapore",
  "postcode": "051531",
  "country": "singapore"
}
```

4. Usually if libpostal gets a city or other toponym wrong, it's because that toponym is not in OSM, and that is indeed the case for both Mararikulam and Aleppey. The latter is also misspelled, official spelling is Alleppey with two l's. Some users have brought up the issue of making the parser more forgiving of spelling errors, which is possible, but it's a nontrivial amount of work, so I'd probably need a company to sponsor it. Aside from the issue of general spelling correction, there's the fact that In India a lot of toponyms are basically transliterations of Indic language words, same is true with Arabic or Hebrew. It might be worthwhile to add valid alternative spellings in OSM. They have tags for this like "alt_name", "short_name", etc. that libpostal will also sample from when building its training set. In general for cities that libpostal gets wrong, the best remedy is to first check OSM for the name, and add anything that's missing. Libpostal will pick it the changes on the next build.

5. The 10%-trained new model has the same problem with the first address, but it gets "NH-21, Raison, 175128, India" correct, probably just from structural features. The first mistake is not a totally unreasonable one to make. Raison is a tiny village with no OSM addresses, so the model would have to be relying on at most a handful of training examples from our places-only training set. Meanwhile there probably are a number of camping sites in the world that are followed by a place name. Libpostal currently ignores commas (so as not to become too dependent on them), but if it didn't, the comma structure in that address would also tend to indicate that Raison is part of the venue name. Even to a human it's unclear, and as such it's probably not something we can reasonably expect a machine learning model to get correct (hype to the contrary notwithstanding). As far as Kullu, in our data it usually refers to the capital town in the eponymous district, so that's why it probably gets labeled as the city, and even with the more powerful model that can revise previous decisions, if Kullu is labeled city, it would be even more likely that it transitioned out of a house name. There is perhaps one tweakable knob that can affect this case, which is the state_district probability. Except for a few countries like the US, we only add state_district with a probability of 5% by default. I've increased that probability to 30% for India, so state_district will be included more often and the parser will be more used to seeing it.

6. Chanakayapuri is misspelled. OSM has Chanakyapuri, and with the correct spelling, libpostal correctly identifies it as city_district. You can add that as an alternative name in OSM if you want. Diplomatic Enclave is not in OSM (there's one listed in Islamabad, but not in New Delhi), so that boundary/point needs to be added as well. In general, India needs a lot of work in OSM, so I'm sure any contributions are welcome. I've asked some of our Indian users if they know of any other open data sets for India that we could use, but so far no luck.

7. Again this may have to do with the hyphenated unit. Also we typically don't add units without a phrase like "#" or "Apt", etc. preceding them (because we're generating the unit expressions, we don't want to create too much unnecessary ambiguity for the parser to deal with i.e. if it had to disambiguate when simple numbers following a road token are part of the road or a unit number). I could maybe justify adding "naked" units if and only if they have a complex structure like a hyphen or a letter so it's easier to distinguish them from ordinary road names.

8. New model gets this one correct, probably with the help of the OpenAddresses data. Some of those data sets do not contain street types (OSM usually does), which helps in these cases.

**Comment by misu200** [comment]
I am just waiting testing the 'parser-data' branch ...because right now is compiling but can't really use it. Having unit, level, po_box, entrance, and staircase its a massive improvment IMHO

**Comment by thatdatabaseguy** [comment]
Libpostal 1.0 has been released into master. You should find that it works much better on addresses all over the world, and includes sub-building information, P.O. boxes, etc. in 30+ languages.

For the Singapore and India cases, the best recourse is going to be to add data to OSM. Even if you can't add the addresses because they're copyrighted or whatever, you can still help map the boundary names, neighborhoods, etc. that are missing. Libpostal picks up updates like that, but it can only ever be as good/accurate as the data that support it.

**Comment by brianmacy** [comment]
Do you have a link on where to go to add data to the OSM?

I integrated the new version.  It said the data files were up to date, though that seems odd.

The new version seems to have a fundamental issue with even the basic addresses:

[6 RAFFLES BLVD, SINGAPORE, 039594, SINGAPORE]
  [house_number] => [6]
  [suburb] => [raffles]
  [road] => [blvd]
  [city] => [singapore]
  [postcode] => [039594]
  [city] => [singapore]

[1 JALAN ANAK BUKIT, SINGAPORE, 588996, SINGAPORE]
  [house_number] => [1]
  [road] => [jalan]
  [suburb] => [anak bukit]
  [city] => [singapore]
  [postcode] => [588996]
  [city] => [singapore]

[18 MARINA GARDENS DRIVE, SINGAPORE, 018953, SINGAPORE]
  [house_number] => [18]
  [category] => [marina]
  [road] => [gardens drive]
  [city] => [singapore]
  [postcode] => [018953]
  [city] => [singapore]


On Apr 7, 2017, 2:55 AM -0400, Al Barrentine <notifications@github.com>, wrote:

Libpostal 1.0 has been released into master. You should find that it works much better on addresses all over the world, and includes sub-building information, P.O. boxes, etc. in 30+ languages.

For the Singapore and India cases, the best recourse is going to be to add data to OSM. Even if you can't add the addresses because they're copyrighted or whatever, you can still help map the boundary names, neighborhoods, etc. that are missing. Libpostal picks up updates like that, but it can only ever be as good/accurate as the data that support it.

**Comment by thatdatabaseguy** [comment]
Then you're not updated. That sounds like it's using the new code and the old model, which would be a disaster. If everything's working, it should download new files. Try clearing out the old datadir, pulling from master, running bootstrap.sh, configure, make and make install. Then try the address_parser client. Here were my results on those addresses:

```
> 6 RAFFLES BLVD, SINGAPORE, 039594, SINGAPORE

Result:

{
  "house_number": "6",
  "road": "raffles blvd",
  "city": "singapore",
  "postcode": "039594",
  "country": "singapore"
}

> 1 JALAN ANAK BUKIT, SINGAPORE, 588996, SINGAPORE

Result:

{
  "house_number": "1",
  "road": "jalan anak bukit",
  "city": "singapore",
  "postcode": "588996",
  "country": "singapore"
}

> 18 MARINA GARDENS DRIVE, SINGAPORE, 018953, SINGAPORE

Result:

{
  "house_number": "18",
  "road": "marina gardens drive",
  "city": "singapore",
  "postcode": "018953",
  "country": "singapore"
}
```

The output you posted doesn't look like any of the bindings, so if you're using something unofficial, that binding probably has to be updated to the new API as well.

**Comment by brianmacy** [comment]
Will do.  When I clean everything out, this is the file I get.  Does this make sense?

http://libpostal.s3.amazonaws.com/models/address_parser/2017-03-04/parser.tar.gz

On Apr 7, 2017, 3:09 PM -0400, Al Barrentine <notifications@github.com>, wrote:

Then you're not updated. That sounds like it's using the new code and the old model, which would be a disaster. If everything's working, it should download new files. Try clearing out the old datadir, pulling from master, running bootstrap.sh, configure, make and make install. Then try the address_parser client. Here were my results on those addresses:


> 6 RAFFLES BLVD, SINGAPORE, 039594, SINGAPORE

Result:

{
  "house_number": "6",
  "road": "raffles blvd",
  "city": "singapore",
  "postcode": "039594",
  "country": "singapore"
}

> 1 JALAN ANAK BUKIT, SINGAPORE, 588996, SINGAPORE

Result:

{
  "house_number": "1",
  "road": "jalan anak bukit",
  "city": "singapore",
  "postcode": "588996",
  "country": "singapore"
}

> 18 MARINA GARDENS DRIVE, SINGAPORE, 018953, SINGAPORE

Result:

{
  "house_number": "18",
  "road": "marina gardens drive",
  "city": "singapore",
  "postcode": "018953",
  "country": "singapore"
}



The output you posted doesn't look like any of the bindings, so if you're using something unofficial, that binding probably has to be updated to the new API as well.

**Comment by thatdatabaseguy** [comment]
Yep, that's the one.

**Comment by thatdatabaseguy** [comment]
As far as OSM, it's pretty easy to edit. Go to https://openstreetmap.org, click Sign Up, create a username, etc. so you can edit. The [iD editor](http://learnosm.org/en/beginner/id-editor/) can be used in-browser to add addresses, places, venues, boundaries, roads, etc. It's usually a good idea to look up the guidelines for each country on the OSMwiki, i.e. https://wiki.openstreetmap.org/wiki/WikiProject_Singapore

**Comment by brianmacy** [comment]
Thanks.  I will look into it.

BTW the issue was that I had a stale address_parser.dat hanging around.  Apparently the new code favors loading it over the new files.  Might consider reversing that to favor the new files.

Brian Macy


On Apr 7, 2017, 3:24 PM -0400, Al Barrentine <notifications@github.com>, wrote:

As far as OSM, it's pretty easy to edit. Go to https://openstreetmap.org, click Sign Up, create a username, etc. so you can edit. The iD editor<http://learnosm.org/en/beginner/id-editor/> can be used in-browser to add addresses, places, venues, boundaries, roads, etc. It's usually a good idea to look up the guidelines for each country on the OSMwiki, i.e. https://wiki.openstreetmap.org/wiki/WikiProject_Singapore

**Comment by thatdatabaseguy** [comment]
Ok, was able to replicate that. Added another housekeeping file for the data version, which will blow away the datadir and other housekeeping files (last update timestamps), and cause it to download the new files.

Essentially the new runtime parser is polymorphic, so can either load the greedy model or the more powerful CRF depending on which file is present. I guess it could prefer the CRF file, 6 of one, half dozen of the other.

**Comment by brianmacy** [comment]
In the first runs, my Singapore end results are about 8% worse with the new parser.  That said, the majority of the problems are in dealing with the #bldg-suite stuff.  Is adding a handful of records to OSM going to resolve that?  I certainly don’t mind putting some effort forward here.

Mostly…

#01-010, 7 My Road, Singapore, 000000, Singapore
 * 01-010 ends up as the house_number and “7 My Road” ends up as the road

7 My Road, #01-010, Singapore, 000000, Singapore
 * 7 is the house_number and “My Road 01-010” is the road

Brian Macy


On Apr 7, 2017, 5:45 PM -0400, Al Barrentine <notifications@github.com>, wrote:

Ok, was able to replicate that. Added another housekeeping file for the data version, which will blow away the datadir and other housekeeping files (last update timestamps), and cause it to download the new files.

Essentially the new runtime parser is polymorphic, so can either load the greedy model or the more powerful CRF depending on which file is present. I guess it could prefer the CRF file, 6 of one, half dozen of the other.

**Comment by thatdatabaseguy** [comment]
Does 8% worse mean just on Singapore? If so, that's not necessarily a fair/accurate assessment because it doesn't take into account how much better it does on the rest of the world.

As far as complex unit numbers, that's a known issue. OSM rarely contains unit information at all, so to help the parser recognize units, we randomly generate them and append them to addresses some proportion of the time. In the data set that 1.0 is trained on, the unit numbers we generated were relatively simple, just 1-6 digits, a letter, or a combination of letter + digits or digits + letter. That covers the majority of cases in most countries, but not the more complex units occasionally found in, say, Singapore like "# 1-010". So the parser has basically never seen a unit number like that. The closest it has seen are probably house numbers in Montreal, which use the "#" sign and often have the apartment concatenated on the left-hand side. So house number would be the closest thing according to the training examples.

I recently added a [commit](https://github.com/openvenues/libpostal/commit/217de3a8a214dab3f731dd555109b12fbc4f7f60) to generate hyphenated numbers like that for units, etc. as well as things like "A-123", "123-A", etc. so on the next training batch it should be able to recognize those.

For OSM, it's more about adding the place names in your data set that don't exist in OSM. Libpostal relies heavily on memorization for places names, and if they're not in OSM or spelled differently, it will almost certainly get them wrong. For addresses, what might also be particularly helpful is adding a bunch of addresses with e.g. addr:block="E" addr:block="C1". That tag is mostly used in Japan (for their bango-style addresses), and that's currently the only place we look for it, but if there were more data in Singapore I could pick it up there as well (libpostal can take care of adding "Block" preceding the number).
