### ISSUE TITLE
Oregon test case

### ISSUE THREAD

**Issue by missinglink** [openvenues/libpostal#170]
expected house number: 17032

```
> 17032 SE McLoughlin Blvd, Portland, OR 97267

Result:

{
  "postcode": "17032",
  "road": "se mcloughlin blvd",
  "city": "portland",
  "state": "or",
  "postcode": "97267"
}
```

**Comment by missinglink** [comment]
Surely an address should never include two postcodes?

**Comment by thatdatabaseguy** [comment]
Assuming this from the model in master? I just sent a sample of the 1.0 model to the whole Pelias group, where house_number/postcode confusion has been worked on extensively (parses virtually every US 5-digit house number case correctly). In particular:

1. There's an index of valid postcode contexts which is computed dynamically from the training set i.e. a number like "17032" could be a postcode in Halifax PA, but without that context it's less likely. This is not a rule, nor does it require that every single postcode be listed in the training data, it just helps the parser learn high positive weights for postcode when there is context and neutral-negative weights when there's not, though other features like the number of digits, surrounding words and the previously predicted tag can still influence the decision.
2. The new Conditional Random Field model uses a much more powerful inference algorithm which optimizes over entire sequences of decisions rather than making N locally-optimal (sometimes suboptimal) decisions and committing to them. So effectively, it might initially think postcode, but once it sees that the next word is part of a road name, it can revise its previous decision, whereas the current model would just commit and keep going.


And there can certainly be an address string with 2 postcodes in the case where the user pasted one of the address lines in twice. Things like this are fairly common in the geocoder logs I've seen:

```17032 SE McLoughlin Blvd, Portland, OR 97267 Portland, OR 97267```

**Comment by thatdatabaseguy** [comment]
New parser in 1.0 nails this, and most other 5-digit house numbers in the US:

```
> 17032 SE McLoughlin Blvd, Portland, OR 97267


Result:

{
  "house_number": "17032",
  "road": "se mcloughlin blvd",
  "city": "portland",
  "state": "or",
  "postcode": "97267"
}
```
