### ISSUE TITLE
Italian addresses with numbers

### ISSUE THREAD

**Issue by Davide-sd** [openvenues/libpostal#176]
Hello,
I've played a little bit with this incredible library and I've discovered a few things that could be improved about the italian language.

Italian addresses are somewhat messy when they contains numbers. Numbers can be expressed with arabic numerals, roman numerals and they can also be written with words (the latter is extensively used in cadastrial datasets, but it's becoming more and more popular in OSM too). Moreover, arabic numeral followed by characters like `'` or `°` or `º` indicates an ordinal number, ie `1' = 1° = 1º` means `primo (first, in english)`. To make things even more messy, roman numerals can also be used to express an ordinal number, so `1' = 1° = I = primo`.

In the following examples, all the inputs refer to the same address expressed in different forms. Therefore, the output should be the same for each query.

**Example 1: arabic vs roman vs text numerals**

	IN: expand_address("Via 4 Novembre, Vicenza, Italia")
	OUT: ['via 4 novembre vicenza italia']
	IN: expand_address("Via IV Novembre, Vicenza, Italia")
	OUT: ['via iv novembre vicenza italia', 'via 4 novembre vicenza italia']
	IN: expand_address("Via Quattro Novembre, Vicenza, Italia")
	OUT: ['via 4 novembre vicenza italia']	

Note that at the moment, none of the results contain 'via quattro novembre vicenza italia'.

**Example 2: ordinal numbers**

	IN: expand_address("piazza giovanni paolo secondo, verona, italia")
	OUT: ['piazza giovanni paolo secondo verona italia']
	IN: expand_address("Piazza Giovanni Paolo 2°, verona, italia")
	OUT: ['piazza giovanni paolo 2° verona italia']
	IN: expand_address("Piazza Giovanni Paolo II, verona, italia")
	OUT: ['piazza giovanni paolo ii verona italia', 'piazza giovanni paolo 2 verona italia']	
	
Question: the result *piazza giovanni paolo 2 verona italia* is not correct, in this case the number `2` would be parsed as the house number. I guess it's been given as a result because it's part of the training dataset?

**Example 3: ordinal numbers**

	IN: expand_address("Piazza San Pio decimo, Treviso, italia")
	OUT: ['piazza san pio decimo treviso italia']
	IN: expand_address("Piazza San Pio X, Treviso, italia")
	OUT: ['piazza san pio x treviso italia', 'piazza san pio 10 treviso italia']
	IN: expand_address("Piazza San Pio 10°, Treviso, italia")
	OUT: ['piazza san pio 10° treviso italia']

Is there anything I can do to improve the library?

**Comment by thatdatabaseguy** [comment]
Hi @Davide-sd,

Thanks for trying libpostal. So, it seems like there might be a few misconceptions here.

1. We do not expand every possible way of writing a number to every other possible way of writing it. The output of ```expand_address``` can be thought of as a set. The goal is simply: if two addresses mean the same thing, then ```len(set(expand_address(a1)) & set(expand_address(a2))) > 0```. As such, we don't normalize "4" to "quattro" (spellout), only "quattro" to "4" and "IV" to 4. This way "Via Quattro Novembre", "Via 4 Novembre" and "Via IV Novembre" will all have at least one expansion in common.

2. parse_address uses machine learning. The expand_address API does not (other than language detection, which cuts down on the number of possible meanings for abbreviations). expand_address is entirely rule-based, again with the goal that two matching addresses should share at least one expansion. As such, we simply expand all Roman numerals to Arabic numerals regardless of how conventional it is to use them in a given context (generally no one would write "Giovanni Paolo 2", but they might write "1908" instead of "MCMVIII"). Also, since Roman numerals can be ambiguous, especially in the case of a single "I", we retain one form of the string without the conversion, so the set still contains the "Giovanni Paolo II" version as well.

3. I'm seeing a bug in the above output, which is that numeric expression parsing is not working correctly if the spelled-out number is followed by a comma. I've just [added a fix for that case](https://github.com/openvenues/libpostal/commit/b464eb6c07a88ea2591917727b3bc53b8b989759). I'll also be adding another normalization for an upcoming contract which strips ordinal suffixes, so normalizing "10°" to "10" (that way "X" and "10°" will normalize to the same string as well).

**Comment by Davide-sd** [comment]
Hello @thatdatabaseguy ,

thank you for all the clarifications! :)

Indeed, dealing with roman numerals is always difficult.
Because this library have to take into account for several languages, I have another question: would it be possible to normalize from roman numerals to arabic numerals only in the case if the hypothetical roman numeral is separated by the rest of text characters? This example should better explain what I mean:

	IN: expand_address("via 14 luglio, vicenza, italia")
	OUT: ['via 14 luglio vicenza italia', 'via 14 luglio 6cenza italia']

In this case, the normalization rule converted `vi`cenza as `6`cenza, even though there is no white space nor dash character between them.

**Comment by thatdatabaseguy** [comment]
That's odd, only happens with the 14 Luglio example, not the Via 4 Novembre, which is also in Vicenza, or the word Via itself. Roman numerals are supposed to only be converted if they encompass a full word. I'll look into it.

**Comment by thatdatabaseguy** [comment]
Ok, found the Roman numeral issue. It's fixed in master as of https://github.com/openvenues/libpostal/commit/413c584f08082e25fb599b741c4b5eebef4e365a.

**Comment by thatdatabaseguy** [comment]
Hey @Davide-sd, with the merge of #184 and #186, the following inputs:

- "Piazza San Pio decimo, Treviso, italia"
- "Piazza San Pio X, Treviso, italia"
- "Piazza San Pio 10º, Treviso, italia"
- "Piazza San Pio 10°, Treviso, italia"

will all share "piazza san pio 10 treviso italia" as a normalization. Pull the latest from this repo and reinstall to pick up the changes.
