### ISSUE TITLE
US Address parsing error (v1.1)

### ISSUE THREAD

**Issue by coachwei** [openvenues/libpostal#199]
Just tried libpostal v1.1. The following address

`152 O Street NW, District of Columbia, 20001, United States 
`

is parsed into:

```
{country=united states, 
road=o street, 
city=columbia, 
postcode=20001, 
suburb=nw district of, 
house_number=152}
```

**Comment by thatdatabaseguy** [comment]
v1.1 is a dev branch, and using those changes isn't as simple as just switching branches. The model has to be trained using that branch and released so you can download it with ```make```, otherwise you'd be using v1.1 code with a model that expects v1.0.

In 1.0 we were overzealous with including "city" in the training examples, whereas in the US some examples may just include state with no city. I've relaxed that a bit for US/Canada and a few other places for the 1.1 release, but the new training data is still in the process of being generated. Can revisit that address when 1.1 is trained, but closing for now.
