### ISSUE TITLE
libpostal_expand_address may use excessive memory and ultimately fail for certain input

### ISSUE THREAD

**Issue by nathangrand** [openvenues/libpostal#200]
Hi,

If libpostal_expand_address is used for the following address:

I I2 E E I2 I I O I2 I E I E OE!O 74 E2 E 26 I EO E 100, CHEONGJU-SI, 12345, Republic of Korea 

...the expander does not return a result before the process is killed for using too much memory (over 9.5G). This was tested using the C API example normalization code from the docs against a version of libpostal built today (5780a08).

The first part of this address is obviously ridiculous, but nonsense like this does appear in data. Is there a change that can be made so that the expander doesn't crash when it encounters such input?

**Comment by thatdatabaseguy** [comment]
So that wasn't a memory leak or any bug, just that if we treat garbage strings like that as a regular English address (language classifier predicts a ~5% probability that it's English, which is just above the threshold where we would consider the English abbreviations), there are millions of possible interpretations for what it could mean ("E" can be the letter "E" or "East", "I" can be the letter "I", "Interstate", "Island", or the Roman numeral for 1. Then multiply all of that by the outer loop which does all possible hyphenations, etc.)

Luckily our string tree iterator precomputes the number of permutations before looping through them, so rather than trying to determine whether it's garbage input a priori, it's easy to short-circuit the process if the number of permutations exceeds some theshhold n. Setting n=100 for both the outer and inner loop (~10k strings max, 20k with Roman numerals, which are done in post-processing) seems reasonable.

Pull https://github.com/openvenues/libpostal/commit/a7e67c4967b9f12c2461e14cc4db2662309a7fb8 to pick up the changes. Fixes this and similar issues.

**Comment by nathangrand** [comment]
Makes sense, thanks for the quick change

**Comment by thatdatabaseguy** [comment]
No worries.
