### ISSUE TITLE
Incorrect address parsing examples

### ISSUE THREAD

**Issue by coachwei** [openvenues/libpostal#206]
Below are  some incorrect parsing results from V1.0:

1.  `Calle Cocodrilo #373, Sm. 51, Mz. 23, Lote 10, Cancún, Quintana Roo, 77533, Mexico`

parsed into:
`{
"road": "calle cocodrilo",
"house_number": "#373",
"road": "sm. 51 mz. 23 lote 10 cancún quintana roo",
"postcode": "77533",
"country": "mexico"
}`

2. `Lebanon`
parsed into:
`{
"city": "lebanon"
}`

3. `47 HILL ROAD, PINNER, MIDDLESEX, HA5 1LB`
parsed into:
`{
"house_number": "47",
"road": "hill road",
"city": "pinner middlesex",
"postcode": "ha5 1lb"
}`

4. `Batley, WF1 7 9TB, United Kingdom` got parsed into:
`{
"road": "batley wf1",
"house_number": "7",
"postcode": "9tb",
"country": "united kingdom"
}`

5. `Ndola, Copperbelt, Zambia` got parsed into:
`{
"country": "zambia", 
"road": "ndola copperbelt"
}`

**Comment by thatdatabaseguy** [comment]
Can you separate this into one address/pattern per issue? It's fine if there are multiple examples of the same pattern, but I want to avoid never-ending threads with many distinct sub-problems.

**Comment by coachwei** [comment]
@thatdatabaseguy  done. Separated into two categories, and updated the original ticket. Thanks.

**Comment by thatdatabaseguy** [comment]
Oh, sorry I meant opening 5 separate Github issues. I'll add them.

**Comment by thatdatabaseguy** [comment]
I think the ```Batley, WF1 7 9TB, United Kingdom``` case is going to have to be a "won't fix".

That's not a standard postal code format for the UK, probably just a typo. The correct format is "WF17 9TB" with only one space, and adding a new format for the UK would blow up the size of the postcode index, which I'm not prepared to do unless this format is very common.

We essentially store every possible postal code in a trie plus a graph of postal codes to observed admin contexts. When we see a phrase that might be a postal code, we check the phrases on its left and right to see if there's valid admin support for this being a postal code (this is mostly for places like the US that have numeric-only postcodes, "10001" could simply be a house number). In a trie, strings with a shared prefix share storage, but adding an optional space to every UK postcode essentially doubles the size of that part of the trie. It creates double the number of rows in the postcode-admin graph. The UK has about 2 million distinct postcodes, and is the dominant factor in the size of the postcode index overall, so doubling everything in the UK means basically doubling the size of the postcode index, and I can't ask all of our users to pay that cost for a single edge case.

Luckily, you can fix that example and anything like in a preprocessing step by searching the string for a variation of Google's UK postcode regex [here](https://chromium-i18n.appspot.com/ssl-address/data/GB) with the space added, and simply replacing it with the no-space version. Here's an example in Python.

```python
import re
pattern = re.compile("(?:((?:AB|AL|B|BA|BB|BD|BH|BL|BN|BR|BS|BT|BX|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)\d) ([\dA-Z]? ?\d[ABD-HJLN-UW-Z]{2}))", re.I)

s = "Batley, WF1 7 9TB, United Kingdom"
assert(pattern.sub("\\1\\2", s) == "Batley, WF17 9TB, United Kingdom")
```

libpostal can parse the "WF17 9TB" form perfectly:

```
> Batley, WF17 9TB, United Kingdom

Result:

{
  "city": "batley",
  "postcode": "wf17 9tb",
  "country": "united kingdom"
}
```

**Comment by thatdatabaseguy** [comment]
Cancun example is unlike anything I've seen. The manzana/lote (block/lot) format is something I'm working on for 1.1 but have never seen it combined with a numeric house number before. It's always e.g. "Calle Cocodrilo Mz. 23, Lote 10". I speak Spanish but have never seen something like "Sm. 51" in an address - apparently it means "supermanzana" which is like a "super block", so guessing some kind of a city division, but I haven't found any polygons in OSM that could be used for our training addresses. Might be specific to Cancun. The data's there at least in [OpenAddresses's Quintana Roo source](https://github.com/openaddresses/openaddresses/blob/master/sources/mx/quintana-roo/statewide.json), but we'd probably have to process the source data directly on the libpostal side. I made an issue for it in #211.

As far as the city name, that's related to the "coastal orphan cities" problem (#203 and https://github.com/openvenues/libpostal/issues/27#issuecomment-292740044) which will be fixed in 1.1.

**Comment by thatdatabaseguy** [comment]
```47 HILL ROAD, PINNER, MIDDLESEX, HA5 1LB``` is also a "won't fix".

[Middlesex](https://en.wikipedia.org/wiki/Middlesex) is the name of a historic country that's been part of Greater London since 1965. It's not in any of our input data sets like OSM, GeoPlanet, etc. and therefore not included in libpostal. If you can convince the OpenStreetMap UK team to add the historic counties, we'll pick them up. Otherwise, I'm chalking it up to "this is part of the 0.5% libpostal gets wrong that you'll have to be able to tolerate when using it."

**Comment by coachwei** [comment]
@thatdatabaseguy  thanks! you are awesome.
