### ISSUE TITLE
AddressParser returns result with all lower case

### ISSUE THREAD

**Issue by tracyliu94** [openvenues/libpostal#207]
For example, 
I called
AddressParser.parseAddress("1 Main Street, Los Altos")

Then the parser returned the road and city all in lower case: main street, los altos.
Is it possible to get the road and city name with first letter capitalized like "Main Street", "Los Altos"?

**Comment by thatdatabaseguy** [comment]
No, sorry. Most of the parser internals work on lowercased input, and because we have to do a few things that might change the tokenization of the original  input (like converting HTML entities and normalizing various forms of hyphens), we have to first normalize the string, label each token of the normalized string using our sequence model, and then group contiguous tokens with the same label to form the output responses you see. If for instance there were 10 tokens in the original string and 9 in the normalized version, we could not simply label the normalized input and then map the labels to the tokens in the original input. Doing so would work in the vast majority of cases, but could lead to corrupt parses or worse, out of bounds accesses in cases where the tokenization was affected.
