### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Saurabh3012** [openvenues/libpostal#208]
Need help with:

Can you explain the work flow to understand the project from the scratch? 

Gone through the blog already. Is there some documentation available?

Thanks.

**Comment by thatdatabaseguy** [comment]
Hi @Saurabh3012, I'm assuming you mean training data generation. I've said this a few times in other issues but the goal with libpostal was not really for people to train their own models. Our focus is more the application-level library that every geocoding-based application can use, so the documentation is more focused on the user-facing parts of the library rather than the training data pipeline. Re: the original question about recipients, I've thought a little about recipient generation for the "care of"-style addresses, but it's not a priority for libpostal at this time. Again, we're more interested in what people search for in an online GIS system than what they write on an envelope.

If you're familiar with Conditional Random Fields and/or NLP, feel free to create your own model for Indian mailing addresses.
