### ISSUE TITLE
MD (Maryland USA) -> mead ??

### ISSUE THREAD

**Issue by invious** [openvenues/libpostal#216]
MD in an address seems to normalize to mead?

**Comment by thatdatabaseguy** [comment]
The expand_address API will try *all* possible expansions and does not make any attempt to disambiguate. I've detailed this in other issues, but the results of expand_address are not meant to be interpreted as a ranked list (so the first result from the list cannot be expected to be the best one and might be nonsensical to a human), but as a set. Since not all programming languages have native sets, we return them as a list and simply document the fact that it's unordered.

For e.g. "Baltimore, MD" these would be all the potential expansions, one of which contains the correct expansion "Maryland":

```
baltimore mead
baltimore maryland
baltimore md
baltimore 1500
baltimore medical doctor
```

While only one of these results is correct, the set formulation is still useful in operations similar to a SQL JOIN or a set intersection.

**Comment by invious** [comment]
ah this makes a lot of sense. I realized this afterward. I am using address as a key for dict and this was exactly what i needed. thank you.

**Comment by invious** [comment]
I did however find an edge case, i think:

```
addr_hash('209 ST MICHAELS CIRCLE ODENTON MD 21113')
u'209 street michaels circle odenton mead 21113'
addr_hash('209 St.Michaels Circle, Odenton, MD 2113')
u'209 st.michaels circle odenton mead 2113'
```
Data comes from hand-inputted excel sheets

**Comment by thatdatabaseguy** [comment]
Added an issue for that case in https://github.com/openvenues/libpostal/issues/218
