### ISSUE TITLE
Parameter confusion

### ISSUE THREAD

**Issue by Mayberg** [openvenues/libpostal#220]
I am trying to use Libpostal to parse an address in a known country, but whatever parameters (such as language and country code) I pass into Libpostal it does not appear to change how it parses the address. 

Can you please provide some guidance on what these parameters do and how to invoke them using the command line.

**Comment by thatdatabaseguy** [comment]
The parameters to the parser are not currently used for anything, so I've removed their descriptions from the address parser client to avoid confusion. Originally I tried building a known-country model but it performed significantly worse than the global model (a several percentage point drop in accuracy IIRC, which made it practically unusable). The language parameter can control which dictionaries are used to aid in the parse, though have never seen it change a result.

If libpostal's getting some pattern of addresses wrong, just post an example and chances are it can be fixed in the training data.
