### ISSUE TITLE
Help with modifying dictionaries

### ISSUE THREAD

**Issue by scotbond** [openvenues/libpostal#221]
Hi,
it seems I'm missing something, trying to modify or add dictionary files to specific language (he).
But can't seem to make those changes effective.
What are the steps required to make changes apply? the Readme say nothing about it.
I tried to rebuidling, cleanning, restarting, etc..
Thanks

**Comment by thatdatabaseguy** [comment]
If you make a pull request to this repo with your changes, the CI will automatically build the dictionary files and push them out to S3. Note: this will only affect the expand_address API in the immediate term because the parser model has to be retrained with the new dictionaries, and retraining takes multiple days.
