### ISSUE TITLE
Centos build was successful but address_parser killed itself

### ISSUE THREAD

**Issue by thethree** [openvenues/libpostal#226]
I was trying to make a PHP extension for it.. so I followed the PHP-postal instructions, and successfully created the extension.

However, the PHP parser seems very slow and sometimes give me 500 error.  So I figured that I should try the command line and see if that was the reason.   If I run ./src/address_parser, I see this:

```
[~/dev/libpostal]# ./src/address_parser
Loading models...

Welcome to libpostal's address parser.

Type in any address to parse and print the result.

Special commands:
.exit to quit the program

> Killed
```

I didn't do anything, so just after 1-2 seconds, it killed itself.  Any suggestions?

BTE, when I build the lib, I had to run this:

```export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig```

Otherwise I will have this error when i build php extension:

```
configure: error: php_postal support requires libpostal. Use --with-libpostal-dir=<DIR> to specify the prefix where libpostal headers and library are located

```

And sometimes I just get this:

```
root@server [~/dev/libpostal]# ./src/address_parser
Loading models...
Killed
```

and memory on my vps:

```
root@server [~/dev/libpostal]# free
             total       used       free     shared    buffers     cached
Mem:       6291456    5395068     896388     399684          0     675336
-/+ buffers/cache:    4719732    1571724
Swap:            0          0          0
```

**Comment by thatdatabaseguy** [comment]
The address parser model uses ~1.8GB of memory, and it looks like there's only 1.5GB free on that box, so that's why it's being killed. You'll need to either free up some memory currently being used by other applications or upgrade to a machine with more memory.

See [my response in another issue](https://github.com/openvenues/php-postal/issues/1#issuecomment-216975122) about PHP performance. It's not that the PHP parser is slow, but there's a one-time startup cost of loading the models from disk into memory such that the first request may *seem* slow. In other languages this happens at "import" time but in a web context, PHP may not load the extension until the first request is made. However it's simple enough to prime the server by parsing any single address as part of the server start routine, and then every subsequent request will be fast.

**Comment by vietopq** [comment]
Hi  albarrentine, 
I have problem "configure: error: php_postal support requires libpostal. Use --with-libpostal-dir=<DIR> to specify the prefix where libpostal headers and library are located" too.
I don't know what is "--with-libpostal-dir". I installed lib in "/var/libpostal" and set data dir in "/var/temp/data-listpostal". could you help me ? 
Thanks!

**Comment by albarrentine** [comment]
@vietopq for the PHP bindings, that `--with-libpostal-dir` in your case should be `/var/libpostal` (same as the `--prefix` you used in the libpostal C library's configure), although if pkgconfig is installed, the PHP configure script should already know where libpostal is installed.
