### ISSUE TITLE
Romania address( city and district)

### ISSUE THREAD

**Issue by coachwei** [openvenues/libpostal#239]
Input:

`Splaiul Unirii 16, 4th Floor, Bucharest, 4 District, 040035, Romania`

Output:

```
                road:splaiul unirii
                house_number:16
                road:4th floor bucharest
                house_number:4
                road:district
                postcode:040035
                country:romania
```

It should be:

```
                road:splaiul unirii
                house_number:16
                floor:4th floor
                city:  bucharest
                city_district:4 district
                postcode:040035
                country: romania
```

**Comment by thatdatabaseguy** [comment]
That address is not in OSM. Please feel free to add it.

- the postcode "040035" doesn't exist in OSM, can add that as "addr:postcode" on the address and maybe a few others in the area to ensure it's trained
- the Romanian name for the Bucharest district is "Sector 4" rather than "4 district". We will use English names if they're provided. Please add "name:en" to the boundary in OSM: https://www.openstreetmap.org/way/66259741, can do the same for other sectors if you wish.
