### ISSUE TITLE
Normalization transliterates addresses

### ISSUE THREAD

**Issue by marvinrichter** [openvenues/libpostal#245]
Is it on purpose that normalization transliterates addresses? Because in the examples in the README it doesn't.

```
> ./src/libpostal "Děčínská 1, 18000 Praha, Česká republika"
decinska 1 18000 praha ceska republika
```

**Comment by thatdatabaseguy** [comment]
Yes, the reason those specific README examples had non-transliterated forms is because libpostal used to not transliterate the canonical form of abbreviations if they had accents (so if "strasse" normalized to "straße", the rest of the string would be transliterated, but not "straße" itself, which has now been changed).

Libpostal's normalizations are used more for duplicate detection purposes, so two addresses typed with and without accents could still match e.g. "Děčínská" and "Decínska".

I've updated the README examples.

**Comment by thatdatabaseguy** [comment]
The official language bindings have options to turn off transliteration if you prefer. In Python it would be `expand_address(u'Děčínská 1, 18000 Praha, Česká republika', latin_ascii=False, transliterate=False, strip_accents=False)`. These options are not implemented in the command-line client, which uses default options.
