### ISSUE TITLE
Option to output the canonical word for street, apartment, etc?

### ISSUE THREAD

**Issue by jefffriesen** [openvenues/libpostal#246]
When using the `parse` function, is there a way to get a canonical word in the result?

For example, parsing these addresses give different `road` values:
```
1060 Pine Street Boulder, CO   // {value: "pine street", component: "road"}
1060 Pine St Boulder, CO       // {value: "pine st", component: "road"}
1060 Pine St. Boulder, CO      // {value: "pine st.", component: "road"}
```

Similarly, apartment numbers do the same:
```
1060 Pine St Apt 10 Boulder, CO   // {value: "apt 10", component: "unit"}
1060 Pine St Apt. 10 Boulder, CO  // {value: "apt. 10", component: "unit"}
1060 Pine St Unit 10 Boulder, CO  // {value: "unit 10", component: "unit"}
1060 Pine St #10 Boulder, CO      // {value: "#10", component: "unit"}
```
(btw, thank you so much for including aparment numbers. I've been waiting a year for that!)

I'm hoping there is an option to get a standardized output from these variations. I know `expand` will expand to all known expansions, but that's different than what I'm looking for. I'm hoping that libpostal can pick a canonical value and replace the original with it.

My use case is that I am creating unique identifying key for each address so that I can take multiple datasets and join them based on this unique key. I realize this is what `expand` is designed for. I've used that by expanding both addresses and looking for a match between any of the expanded elements. In some of my scripts it takes hours to do this matching, even with caching the expansion. And that expanded address is not easily stored in a column in the database.  

I realize matching on addresses is not ideal. But if I can do what I'm suggesting I think mis-matches will be far less than my other alternatives.  

So what I'm looking for is something like this:
```
apt, apt. apartment, unit, # => apartment 
str, st., st, street => street
```

What it actuall expands to doesn't even matter as long as it's consistent. Does libpostal have an option for retrieving the canonical form of these words?

Thanks!

**Comment by jefffriesen** [comment]
I would use this feature in other ways. For example, taking addresses entered by user and storing and displaying them later in a standard way. So all displayed addresses that have a street would be displayed as `Street` instead of combinations of `St`, `St.`, and `Street`. 

Even if the canonical output form is `Street` and I wanted to display them as `St.` it's an easy regex compared to having to think through and code all combinations for all street types.

**Comment by thatdatabaseguy** [comment]
Hey @jefffriesen, in the parser we try to stay close to the input, so there is no option to return canonical forms of abbreviations. Even if there were, `St` can mean `Street`, `Saint`, `State`, etc. in English, plus other meanings in other languages (and as an international project, we've been deliberate and intentional about supporting multiple languages and cultures from the jump), and it could also simply be first/middle initials or part of a company name like ST Dupont. Our brains do a wonderful job at this sort of disambiguation but for machines it's more difficult. Any simple rule-based heuristics we can think of for picking the correct expansion have many counterexamples, especially internationally and when considering minority language communities (libpostal considers Spanish a default language in the US, even if the US refuses to acknowledge as much).

It may be possible to train a reasonably good learning model for the disambiguation task, but in most geocoding applications I've seen, the end goal is to match to some set of geocoded addresses anyway, as you describe, and `expand_address` will work for those kinds of JOINs. In both Postgres and Elasticsearch it's possible to store and index an array of keys per document/record. In MySQL or another database you can create a one-to-many table that contains the expansion and the address id, indexed on the expansion value and query that way.

You may also be interested in my new project [lieu](https://github.com/openvenues/lieu), which uses libpostal expansions to do address and/or fuzzier POI/venue matching based on similar names. It works on GeoJSON files with standard OSM-like property names (which may come from a libpostal parse) either as a standalone script using a LevelDB for smaller data sets, or on Spark for larger data sets. It has already been used at scale to match tens of millions of points. That would be more of a batch-processing application, but there are plans currently in the works to make a server version backed by Elasticsearch as well.

I think for display the best option is to match your records with a high-quality data set like OpenStreetMap, OpenAddresses, or a government data set, and use those as the standardized forms instead of the user input. That's what a model would be trained on anyway, and as such a model could not do better and would very likely do worse than matching with clean, standardized  data.

**Comment by elyksenyah** [comment]
Hey tdg,
Re your last paragraph; I agree completely. 
Do you know of any projects that would be useful as a starting point around this?
It's easy enough to think of simple methods to match against large, high-quality datasets. But it simply get's complex quickly.

**Comment by thatdatabaseguy** [comment]
@elyksenyah as mentioned, the lieu project (https://github.com/openvenues/lieu) does deduping, takes GeoJSON as input and runs on Spark against very large data sets. I haven't written anything about lieu yet, but it's really great for venue matching and can do address-only matching (exactly what you're describing) as well. In the next version of libpostal I'm moving the core functions for near-dupe hashing and dupe-checking to C as part of this repo, and will be able to improve address matching as part of that work. It already includes all of the multilingual goodness from libpostal's expand module, language detection, abbreviations, numeric expressions, transliteration, etc. Definitely use lieu rather than coming up with a method from scratch.

**Comment by jefffriesen** [comment]
@thatdatabaseguy 

I really appreciate your curation of this project, including your non-goals. Makes sense about it not generating canonical forms of abbreviations. 

For displaying nice addresses, your suggestion to match expanded addresses against datasets like OpenStreetMap is great. 

Lieu looks really interesting. On my first read it didn't make sense how venue deduping would solve my matching problem. But looking at the [output format](https://github.com/openvenues/lieu#output-format) now I get it. 

I'm going to close this issue. Thanks again.
