### ISSUE TITLE
It would be useful to load dataset independently of build.

### ISSUE THREAD

**Issue by sporkmonger** [openvenues/libpostal#25]
Mostly for Dockerfile scenarios where a 2GB image is undesirable.

**Comment by thatdatabaseguy** [comment]
That makes sense. Have been thinking about something similar for packaging reasons.

It would involve moving the data dir into a config that's loaded at runtime, which also makes it easy to move the data dir, etc.

**Comment by PedroMDuarte** [comment]
Hello, thanks for a great piece of software!  I was wondering, are the datasets required at runtime for address expansion and parsing?, or are they only required to train the models?  I am thinking about deployment and not sure if I can get away with a light installation that does not need to keep the dataset around.

**Comment by thatdatabaseguy** [comment]
Hey Pedro - yes, the data files (not the original data sets, which are at least 10x larger, these are just the learned parameters/weights of the model) are required at runtime. This ticket is more about doing compilation as a separate step, which is still a good idea, though I'm a little worried about introducing additional steps beyond the configure/make/make install workflow.

libpostal's a bit unique in the open source machine learning world. At companies like Google, etc. it's fairly standard to see models that take up 1G of RAM or more, but when those companies publish anything in the open, they usually only publish code or an opaque one-off trained model and keep the data locked up on private servers (not necessarily because they're evil, but because there are licensing/privacy issues, etc) such that the impressive results in the demo can't actually be recreated or generalized. Using OpenStreetMap for libpostal breaks that data monopoly, but it does mean getting the open-source world accustomed to larger download sizes than what we've come to expect.

The current parser needs about 1.5G of disk space (1G memory) - this will increase a bit when the new model in the [parser-data](https://github.com/openvenues/libpostal/tree/parser-data) branch is released. Expansion needs ~710M, which is mostly the language classifier. If you know the language being used a priori, it is possible to run libpostal expand_address using about 10M of disk/RAM.

Generally the size of the libpostal models is a concern and attempting to make them smaller (for mobile, etc.) is on the longer term todo list, but only if it's possible without sacrificing too much in terms of accuracy.

**Comment by thatdatabaseguy** [comment]
@sporkmonger forgot to update this one, but this can be closed as well.  You can do ```./configure --disable-data-download``` as of #120.
