### ISSUE TITLE
Possible issue with recognizing postal stations.

### ISSUE THREAD

**Issue by aiacovella** [openvenues/libpostal#252]
Given the following address:

JOHN Doe 8798 JAMES ST PO BOX 4001 STN A VICTORIA BC V8X 3X4 BC

The following is parsed:

[
    {
        "label": "house",
        "value": "john doe"
    },
    {
        "label": "house_number",
        "value": "8798"
    },
    {
        "label": "road",
        "value": "james st"
    },
    {
        "label": "po_box",
        "value": "po box 4001"
    },
    {
        "label": "house",
        "value": "stn a"
    },
    {
        "label": "city",
        "value": "victoria"
    },
    {
        "label": "state",
        "value": "bc"
    },
    {
        "label": "postcode",
        "value": "v8x 3x4"
    },
    {
        "label": "state",
        "value": "bc"
    }
]

Note that the postal station A "stn a" is parsed as a house.

**Comment by thatdatabaseguy** [comment]
Since PO boxes are practically nonexistent in OSM, we've taught libpostal to recognize them by [generating](https://github.com/openvenues/libpostal/blob/217de3a8a214dab3f731dd555109b12fbc4f7f60/resources/addresses/en.yaml#L581-L651) simple patterns like "PO Box # 1234", etc. in multiple languages in the training data. It's not all that sophisticated but luckily neither are the vast majority of PO box numbers, so handling the most common case was a relatively easy win.

Can you explain what a postal station is and how frequently it's used? If it's frequent in Canada, we can generate a new pattern for it but it'll require some refactoring since we currently assume only one numbered phrase per PO box. If it's just that one address or only occurs in a few cases, I'd say "STN A" as `house` is an acceptable parse (in fact it might even help in geocoding to a post office building for example).

**Comment by aiacovella** [comment]
[This](http://www.thecanadianencyclopedia.ca/en/article/postal-system/) contains a definition of what a postal station is. Excerpt: "Postal outlets or retail outlets are found in stores and businesses for the convenience of the public. In these, the owner of the business acts as the postmaster and provides a postal clerk as necessary"  [This](https://www.canadapost.ca/tools/pg/manual/PGaddress-e.pdf) describes mailing formats. There are a few examples in here of addresses with postal stations. Given that they are used for densely populated areas and are typically retail outlets I think they may have a good amount of usage but I wasn't able to get an example address listing of them.

**Comment by thatdatabaseguy** [comment]
Ok, so we don't optimize for every potential edge case in libpostal, just the ones that come up relatively frequently in practice and/or otherwise derail the parse. Neither of those appears to be the case, and reading that spec I think `house` is actually the right label anyway (barring a new label, but it's not cheap in terms of model size/complexity to add new labels to the parser and affects some downstream users such as the R bindings, so we generally try to reuse existing labels unless there's a pattern that's reasonably common and generalizes to more than one country). If the postal station is basically a business name, it should be handled the same way as other venue/business names.

**Comment by aiacovella** [comment]
I don't believe that they are business names though. The examples I've seen are like 

ACME Company
1879 STATION A 
TORONTO ON M5W1W9 CA

ACME TWO
P.O. BOX 67110 ‐ STATION A 
TORONTO ON M5W5M5 CA

So they are names like Station A, Station B etc.

**Comment by thatdatabaseguy** [comment]
They're not exactly business names but even the alphanumeric version is still consistent with something I'd map to `house` in our nomenclature. The `house` tag is overloaded and can be used for venues/companies, named buildings, landmarks, subdivisions, the name of a post office (closest to this case), etc. Any named place that is not a toponym, or part of the street, house number, or sub-building identifier, would usually be tagged `house` in the training data, and postal stations are consistent with the spirit of that tag, even if they're usually simple alphanumerics (note that the doc also mentioned "Station Main", which seems to indicate that there are exceptions).

**Comment by Crenshinibon** [comment]
FYI. In Germany we have "Packstation" which might translate quite well to postal stations in Canada: https://www.dhl.de/de/privatkunden/pakete-empfangen/an-einem-abholort-empfangen/packstation-empfang.html

**Comment by thatdatabaseguy** [comment]
Same applies in Germany - the `house` tag is sufficient to cover this case. Looking up Packstation in OSM you get examples tagged [amenity=vending_maching](https://www.openstreetmap.org/node/4564176790), [amenity=post_office](https://www.openstreetmap.org/node/494270937), [amenity=post_box](https://www.openstreetmap.org/node/313462051), etc. which are similar to the named place definition I mentioned above. This is the right parse under our current definitions. Using a different tag would mean finding and handling all of the existing cases which would be mapped to `house` in the current version of the training data, and I don't think it's worth the time in a case for which I haven't seen any concrete examples in real-world addresses (handling every bit of post office trivia is not a goal of this project - only when it disrupts the geocodable parts of the parse, as was the case for PO boxes in general in the previous version).
