### ISSUE TITLE
[feature request] house_number ranges

### ISSUE THREAD

**Issue by tobwen** [openvenues/libpostal#260]
Could you add interpretation of housenumber ranges? Up to now I've used my own tool to parse German addresses (developed in PHP years ago). I've done it like this:

```
> Hemmerde Hellweg 1-7
{
    range_from: 1,
    range_to: 7,
    range_count: "odd",
}
```
```
> Hemmerde Hellweg 2-8
{
    range_from: 2,
    range_to: 8,
    range_count: "even",
}
```
```
> Hemmerde Hellweg 1-8
{
    range_from: 1,
    range_to: 8,
    range_count: "mixed"
}
```

Actually, my tool also was able to interpolate ranges:
```
> Hemmerde Hellweg 1-7b
{
    "Hemmerde Hellweg 1",
    "Hemmerde Hellweg 3",
    "Hemmerde Hellweg 5",
    "Hemmerde Hellweg 7",
    "Hemmerde Hellweg 7a",
    "Hemmerde Hellweg 7b"
}
```

Perhaps something to add in future?

**Comment by albarrentine** [comment]
The parser model is trained on many different types of house number ranges, and shouldn't have any trouble identifying them. I don't think adding interpolation of that kind is within the scope of libpostal though, definitely not as part of the parser. If German were the only language we needed to handle, then maybe, but this is a multilingual, international parser and there are so many different schemes for what a hyphenated number can mean (in Canada it's {apartment}-{house number}, in Japan it's {neighborhood}-{block}-{building}, in Malaysia there's no consistent format, etc.)

So no, not in this project. But you're more than welcome to implement that on top of libpostal's parse using a regex, etc. on the `house_number` field.

**Comment by tobwen** [comment]
Sure, I've already implemented it in my code; wasn't hard to adapt.

Isn't is possible do rules on language? If "DE", then do "house_number range"; if "CA", then do ...". Just an idea. Thanks for your time.

**Comment by albarrentine** [comment]
That would have to be on country rather than language. We have a high accuracy language classifier trained on address/geographic data, but using language gets tricky because e.g. German isn't only spoken in Germany :-). In Austria, specifically in Vienna if I remember correctly, it's common to append the apartment number with a hyphen so could have examples like "10-15", which look like a numeric range but is in fact house number 10, apartment 15 (in the really large apartment blocks in Vienna there can be multiple hyphens like "10-A-4-15", for {house number}-{block}-{staircase}-{apartment}). I was under the impression that this could be done in Germany as well, but was less common than something like "c/o".

Country may be determinable in a future version, but still think per-country rules seem like they would live in the business logic of a specific application, and are not something we can/should implement generically for everybody. Also would seem to be more of a fit for higher-level languages than C.

**Comment by tobwen** [comment]
> German isn't only spoken in Germany :-).

That's what _de_DE_, _de_AT_ etc. are for :-)
By the way: the delivery notes _c/o_, _p. Adr._, _z.H._, _z.Hd._ and _oViA_ are accepted by Deutsche Post AG, but only a few are part of the DIN.

**Comment by albarrentine** [comment]
With locales like de_AT, it might be confusing from our language classifier's point of view since that's mostly trained on street names alone. It wouldn't be clear for instance clear from the 4-grams in a German street name e.g. "Dorfstraße" whether it's in Austria or Germany any more than "High Street" is all that predictive of countries in the Anglophone world.

Any automated country classification would require toponyms, embedding some place hierarchy in libpostal, and would probably be a separate API post-parsing.
