### ISSUE TITLE
How to get germany result in expand function ?

### ISSUE THREAD

**Issue by my13901** [openvenues/libpostal#263]
Here is an example : input “München Maximilian str. 5” ,Language = de, Output data:

[

    "muenchen maximilian strasse 5",

    "munchen maximilian strasse 5"

]
It is english result and it can't return germany address like "München xxx".
Is there any way to solve this problem?

**Comment by albarrentine** [comment]
So that may look like an English result, but it's really just transliteration and accent-stripping respectively, which are the defaults in libpostal.

The goal of the expand_address API is deduplication i.e. all of the following versions of that address would share at least one expansion in common:

- München Maximilian str. 5
- München Maximilianstraße 5
- Munchen Maximilian strasse 5

With languages written in Latin script we normalize to the ASCII form as it's not easy to recover e.g. "ü" from "ue" or "ß" from "ss".

Note that libpostal's language classifier does detect German in this case since it expands "str." => "straße" (which then gets transliterated to "strasse") instead of the English "street", Dutch "straat", etc. Since German is statistically close to other Germanic languages like Dutch, it's possible to occasionally get those expansions in the results as well.

There are some non-default options for `latin_ascii=False` and `strip_accents=False` in both the C API and most of the language bindings. I wouldn't recommend using them though because the intention of expand_address is to capture those sorts of normalizations. It's not designed for displaying or standardizing addresses into a single form.
