### ISSUE TITLE
Less memory usage in test environment

### ISSUE THREAD

**Issue by ewgRa** [openvenues/libpostal#268]
Can't find information: how to reduce memory usage for test environment?

We have a case, when for testing or local development there is not needed all databases, for example we want to have there only US database. It helps reduce system requirements for local and test environment and make them cheaper.

Is there way to install libpostal only for specific database?

Maybe: ./configure --data=US ?

**Comment by albarrentine** [comment]
Sorry, there's no way to reduce the memory requirements as part of configuration. Libpostal requires 1.8GB of memory and disk space. There's no database involved at present, only a trained machine learning model (it's relatively common for high-accuracy production models trained on large data sets to be about this size - that just comes with the territory).

There are no current plans to train/support per-country models centrally. This project is designed to have basically zero configuration so everyone's using the same model and gets the same benefits, improvements to the parser tend to be geared toward improving global outcomes rather than privileging certain countries/languages over others, and, importantly, parser issues can be reproduced relatively easily without having to replicate everyone's unique setup.

Though it is possible to train smaller models (and at least one user has done it so far in #132), I wouldn't recommend it for a test environment where libpostal's results are used in any of the test cases. A single-country model will not necessarily produce the same results as parsing addresses in that country with the global model. In some cases the single-country model would do better, and in some cases it would do worse, but it's a completely different parser from what would be running on production. It's not possible to extract only US-relevant components from the global parser.

**Comment by ewgRa** [comment]
@albarrentine thanks for explanations.

Now I understand that memory needed for trained model. Small trained model, just for example for one country, maybe not trained for very rare or specific cases is what we need for development cycle.

I will check later #132, and maybe prepare PR for our case if will solve this problem in a best way.

**Comment by piskvorky** [comment]
@albarrentine you write:

> Libpostal requires 1.8GB of memory and disk space. 

but the README says:

> Memory-efficiency: libpostal is designed to run in a MapReduce setting where we may be limited to < 1GB of RAM per process depending on the machine configuration. As much as possible libpostal uses contiguous arrays, tries (built on contiguous arrays), bloom filters and compressed sparse matrices to keep memory usage low.

Is it 1.8 GB or 1 GB? How would one reduce the RAM footprint?

Also, are these large structures in shared memory (mmap, shared among processes)? Thanks.
