### ISSUE TITLE
Adding new address data and retraining models

### ISSUE THREAD

**Issue by nicslos** [openvenues/libpostal#314]
Hi!

as I read in other issues, the main direction of the libpostal library is, to 
train the general model to gradually improve it.
As my company is highly dependent on correct address parsing,
we evaluate the library and the performance is quite good.
So for using libpostal, the challenging question is, how it can be customized.
As for extending the dictionaries and rules, I found some examples in the issues,
but seems to me, that there is no readme or something, that collects all steps which are necessary to add new resources like dictionaries, is it?
As we find address data issues every day and would need for example to add new, not covered address parsing cases to the training data, we would like to either:
- retrain the model on our own (which, as I read, demands lots of computing power and takes up to 2 weeks)
or:
- contribute address data to improve the model publicly

If we went with the second option, how reliable would there be updated models?
As I read in the issues, the quality standards are quite high and 
not all contributions are accepted.

Thanks 
N

**Comment by albarrentine** [comment]
In general, customization/retraining is not a major goal of the project. The focus is on improving the common library for everyone instead of having lots of custom-trained models. There are three primary reasons for this:

1. addresses by themselves are not special or specific to a company/organization (it's more about the data attached to them)
2. training takes a lot of resources, 40GB of RAM, hundreds of GB or disk space, so more hardware than most people have. We're moving to a Spark implementation in v1.1 which should be slightly easier than running a single giant machine, but it's still resource-intensive.
3. with proprietary training data, it's not easy to diagnose why the model isn't performing as well as people were hoping without seeing the model's inputs.

I don't recall rejecting many contributions, but I do have to tell people "99.45% is good enough" sometimes and that we may not be able to fix every error in the same way one would fix a bug in traditional software. When the parser gets something wrong, it's often because there's some pattern that exists in the real world but not in our training data for some reason, and in those cases we simply modify the training data to account for that pattern.

Data contributions are generally welcome, though yes, we do try to start with high-quality data and then perturb it in various ways to look more like examples found in the wild. Since machine learning is very much a garbage-in-garbage-out process, it's always a good idea in supervised learning to pay close attention to the training data.
