### ISSUE TITLE
Regression issue when paring address with "cnr"

### ISSUE THREAD

**Issue by liufang94** [openvenues/libpostal#320]
Hi Awesome libpostal!

I noticed there was a regression when parsing an address with "cnr" as the first word. 
I am not sure exactly when the regression happened, but it was correct before.
For example,

> Cnr Miriam Makeba St Johannesburg Gauteng 2107 ZA
Result:
{
  "house_number": "cnr",        //"cnr" should be part of road 
  "road": "miriam makeba st",
  "city": "johannesburg",
  "state": "gauteng",
  "postcode": "2107",
  "country": "za"
}

> Shop 3 Cnr Rodger Shishi Rd Durban KwaZulu-Natal 3629 ZA
Result:
{
  "unit": "shop 3",
  "house_number": "cnr",       //"cnr" should be part of road 
  "road": "miriam makeba st",
  "road": "rodger shishi rd",
  "city": "durban",
  "state": "kwazulu-natal",
  "postcode": "3629",
  "country": "za"
}

**Comment by albarrentine** [comment]
Hi @liufang94, a regression as in this worked in a previous version and doesn't now?

We don't currently have training examples from OSM that use the "cnr" expression, so the model's probably relying on structural features (house number comes before road most of the time in English). That should be easy enough to add though for the next version.

**Comment by liufang94** [comment]
Thanks very much for your quick response! It would be great if you could
fix it in next version.

Yes, I can't remember when I cloned libpostal last time, but it can parse
"cnr" + other road name to "road" correctly.

Tomorrow I am going to try install a few previous commit and find a working
one.

**Comment by albarrentine** [comment]
Hm, if a previous version (probably v0.3) did get that right, it was probably by accident i.e. the previous model was not using structural features to deal with words where it was uncertain, so it may have simply relied on an unknown word feature, for which the most likely tag was `road`. I wouldn't roll back to that version based on one test case, as there are many other improvements in v1.0 like secondary units (the previous parser for instance didn't have a `unit` tag, so "Shop 3" would not be handled correctly). For machine learning models, it's usually best to evaluate the accuracy by averaging over many test cases and look for material improvements in this average performance rather than only evaluate on individual test cases as we would do in rule-based programs.

**Comment by liufang94** [comment]
Thanks for the explanation. Sorry for some confusion, when I said previous
version, I didn't mean v0.3 or 1.0, I just cloned from master, so I should
have said last "commit". It was definitely some commit after 1.0, the last
time I cloned from github should be either Dec 2017 or Jan 2018. It could
parse secondary unit correctly. thanks.

**Comment by liufang94** [comment]
Hi AI,

My colleague's machine installed libpostal commit:
94a0e842e74598c6d52a4809ea4604b4be25ca60
AuthorDate: Wed Aug 16 15:04:15 2017 -0400
His address_parser can parse "cnr" correctly.
> Shop 3 Cnr Rodger Shishi Rd Durban KwaZulu-Natal 3629 ZA
Result:
{
  "unit": "shop 3",
  *"road": "cnr rodger shishi rd",*
  "city": "durban",
  "state": "kwazulu-natal",
  "postcode": "3629",
  "country": "za"
}

Then I just git clone master and reset --hard to this commit, but my
address_parser can NOT parse it correctly.
> Shop 3 Cnr Rodger Shishi Rd Durban KwaZulu-Natal 3629 ZA
Result:
{
  "unit": "shop 3",
  *"house_number": "cnr",*
  *"road": "rodger shishi rd",*
  "city": "durban",
  "state": "kwazulu-natal",
  "postcode": "3629",
  "country": "za"
}

So the problem seems not in github code. It might be something else used by
the code, which might have been updated after my colleague's installation.

Do you have any idea what that might be?

Thanks!

**Comment by albarrentine** [comment]
Ah, it might have to do with the [deduping release](https://github.com/openvenues/libpostal/releases/tag/v1.1-alpha) and the new root expansion functionality. For root expansions (where we strip something like "N Spring St" down to just "Spring") used in address deduping/matching, [this commit](https://github.com/openvenues/libpostal/commit/e3a252d4eb075f9a5a6bc5fb16dd4495b88af114)
 dealt with the ambiguity between rare street types like "Spring" that can also be part of core street names e.g. "Spring St" and added a few of the street types to synonyms.txt so that they could be treated as known core words e.g. in a case like "Spring St" where "Spring" can also be a rare street type, so anything that's rare/could be a street type was added. When that happens, the dictionaries get rebuilt, and there's a binary that gets built and pushed along with them. If your colleague ran `make` again, he would get the updated file as well. The parser uses those dictionaries as features in the model, so some changes to the dictionaries can cause the runtime parser to have to lose or substitute a variable it used in training, which is the case here.

What I'll do for the moment is remove the entry for "Corner" from the synonyms dictionary, since it's not that common to see something like "Corner St," and then rebuild the dictionaries, which fixes this example. I can't promise there are no other differences though, and I need the majority of that commit to stay intact for the project I'm currently working on. If you need to replicate your colleague's machine exactly, ask him to scp the datadir over to your machine so you have the exact same binary. in future versions of the parser we'll embed the dictionaries it was trained on as part of the model, so adding abbreviations, changing dictionaries, etc. doesn't affect parsing at all until the next training (though people usually want an immediate fix, it usually requires rebuilding the training data).

**Comment by albarrentine** [comment]
Confirmed fixed. Moving that phrase back to synonyms for the next training.

**Comment by albarrentine** [comment]
Scratch that, moved the entries from synonyms.txt to a new street_names.txt dictionary that was planned for originally but wasn't being used. That makes space for a dictionary of words/phrases/abbreviations that occur in street names but are also often part of the core street name. That way it can be handled in the expand module only without affecting the parser.

**Comment by liufang94** [comment]
Thanks very much AI. Confirmed fixed. Sorry for the late confirmation. I had a new phone and got issue to sign in my account. Now I am back.
