### ISSUE TITLE
Parser failure on some 5 digit street addresses

### ISSUE THREAD

**Issue by lushzero** [openvenues/libpostal#45]
There is an odd issue that addresses containing certain ranges of street numbers fail to parse properly. In my case for some (not all) addresses over 10000 seem to cause problems where the parser thinks the street number is the postal code. One of the real world addresses that is causing me problems is: 25050 ALESSANDRO BLVD, STE B, MORENO VALLEY, CA, 92553-4313 . It's a strip mall in CA, USA. Google Maps and USPS have no problem with it thought OpenStreeMap can't find it.

Here is a patch that introduces a test showing the problem.

```
diff --git a/test/test_parser.c b/test/test_parser.c
index db6a11c..9eea212 100644
--- a/test/test_parser.c
+++ b/test/test_parser.c
@@ -71,9 +71,28 @@ TEST test_us_parses(void) {
         (labeled_component_t){"postcode", "11216"},
         (labeled_component_t){"country", "usa"}
     ));
+
     PASS();
 }

+TEST test_us_commercial_parses(void) {
+    address_parser_options_t options = get_libpostal_address_parser_default_options();
+
+    CHECK_CALL(test_parse_result_equals(
+        "25050 ALESSANDRO BLVD, STE B, MORENO VALLEY, CA, 92553-4313",
+        options,
+        5,
+        (labeled_component_t){"house_number", "25050"},
+        (labeled_component_t){"road", "allessandro blvd ste b"},
+        (labeled_component_t){"city", "moreno valley"},
+        (labeled_component_t){"state", "ca"},
+        (labeled_component_t){"postcode", "92553-4313"}
+    )); 
+
+    PASS();
+}
+
+

 TEST test_uk_parses(void) {
     address_parser_options_t options = get_libpostal_address_parser_default_options();
@@ -234,6 +253,7 @@ SUITE(libpostal_parser_tests) {
     }

     RUN_TEST(test_us_parses);
+    RUN_TEST(test_us_commercial_parses);
     RUN_TEST(test_uk_parses);
     RUN_TEST(test_es_parses);
     RUN_TEST(test_za_parses);
```

**Comment by lushzero** [comment]
This is a pretty blocking issue for me, is anyone else able to reproduce this error?

**Comment by thatdatabaseguy** [comment]
Ok, so remember libpostal is a statistical parser rather than a rules-based one, and while it achieves 98.9% full-parse accuracy (on the OpenStreetMap data set), that's not 100% and it will probably always get some cases wrong. In rules-based or regex parsing one might have a rule that says "if it's a five digit number in the first half of the string, it's a house number, otherwise it's a postal code." That's fine for most US addresses, but fails on geocoder input which may simply be "92553 Moreno Valley", not to mention that some countries write their addresses in the opposite order that we do.

libpostal is a language model, not a geocoder like Google Maps, OSM, etc. so it doesn't know or care if the address actually exists or not. The input can be "123 fake st" and libpostal will parse it all the same. For the Alessandro Blvd address, even though it's an obvious parse to a human, I can see the parser getting confused because it sees a 5 digit number which is actually a [valid postal code](https://www.google.com/maps/place/25050+Province+of+Brescia,+Italy/data=!4m2!3m1!1s0x4783cef430da85ab:0x1c067805801fcbb0?sa=X&ved=0ahUKEwiK5eaJvtXLAhWCiRoKHW48DRgQ8gEIGzAA) (just not in the US) followed by "Alessandro" which can also be a city name (not a very common one, granted, but it [exists](https://en.wikipedia.org/wiki/Alessandro,_California)). In my tests, house_number/postcode was one of the more common mistakes the parser made. Often it happens in places that have four-digit postcodes like South Africa, but it happens in the US as well.

For improving predictive performance on patterns like that, we can design and test some new input features. I'd bet that incorporating longer range dependencies such as "there is another known postal code to the right of this token" might help in many of the house_number/postcode mistakes.

I'm retraining the parser soon (toward the end of the month) with some new tags and a larger training set. Will try to account for this case. If it parses successfully with the new model, I'll add the test case to the build so future models can check for regressions.

In the meantime, if you know that your addresses are in the US, you could also write your own rule on top of the output from libpostal which says "if there are two postal codes, the first one is a house number." Parse results are returned in order, so I think that should do the trick.

**Comment by lushzero** [comment]
I get that the problem is difficult but in this case the failure state has 2 postal codes in the returned data which seems like it should be invalid. I would also check this further as it seems like this error happens on numbers that are not valid US or international postal codes. 

Compounding that the errors are not randomly distributed, it means that if you are in moreno valley or huge consecutive swaths of say los angeles like olympic blvd you are out of luck. That's seems blocking to me. In miles and miles of a very big american city there is 0% success rate. At least for me that's a blocker.

**Comment by thatdatabaseguy** [comment]
I agree with you that it's one of the parser's weaker points currently, but a 0% success rate for miles and miles of a very big American city may be a bit of an exaggeration of how pervasive the problem actually is. Certain parse mistakes like this can be particularly annoying and seem like they should be obvious/avoidable, but it's important in these things to look at the actual numbers to characterize what kind of mistakes are being made and how often.

Here's a quick test script (using the Python bindings for succinctness) that will test every five digit house number from 10000-99999 using the street name supplied and report the accuracy:

```python
from postal.parser import parse_address

def test_house_number_range(street_name, min_house_number=10000, max_house_number=100000):
    correct = 0
    for i in xrange(min_house_number, max_house_number):
        result = parse_address('{} {} Los Angeles CA 90064'.format(i, street_name))
        if result and result[0][1] == 'house_number':
            correct += 1

    return float(correct) / (max_house_number - min_house_number)

print test_house_number_range('Olympic Blvd')
```

On that test libpostal gets 99.72% correct, which is only 246 errors out of 90000 hypothetical addresses on Olympic Blvd. Analyzing the specific errors, none of them were consecutive numbers, but it's true that they're not evenly distributed. 82% are in the 30000-69999 range and there are 0 errors in the 10000-19999 range (probably because the 10000 range is more common in house numbers).

Doing the same for Alessandro Blvd yields a 94.9% success rate, less impressive, but not unusably deficient in most applications.

Re: duplicate postal codes, it's usually a mistake to return more than one, but not always. The main issue with restricting the labels libpostal returns is parsing geocoder input. People type all sorts of bizarre things into geocoders: full paragraphs, copy-pasting the same address multiple times, CSV files full of postcodes, etc. and since geocoders are one of the primary use cases, I didn't want to create cases where the parser couldn't make progress because it ran out of unused labels.

The house_number/postcode error is one of the larger error classes in the model's confusion matrix, so is definitely on my to-do list. The longer-range dependency feature I mentioned should improve results in this category for a number of countries including the US.

Updates to come.

**Comment by lushzero** [comment]
Thank you for the thoughtful response, that is encouraging. I look forward to seeing improvements in this regard. To me it's important to impress that numbers like 99.72% and 82% are a bit misleading because they are referring to percentages of theoretical addresses. But addresses aren't theoretical, they are physical properties and it so happens that a LOT of them fall into this issue. 

About 10% of the actual olympic blvd in los angeles falls into this. It's a similar grim picture on many of the major E to W roads there. I don't think it's unfair to say that huge swaths of actual addresses are unparseable. Obviously big cities with long roads that are sequentially numbered are more likely to hit this issue. Here is map showing in real terms the length of olympic in los angeles that can't currently be parsed (in blue).

http://i.imgur.com/WH4v3vl.png

**Comment by thatdatabaseguy** [comment]
Libpostal 1.0 can now correctly parse this example, and probably every other 5-digit house number in the US as well.

```
> 25050 ALESSANDRO BLVD, STE B, MORENO VALLEY, CA, 92553-4313

Result:

{
  "house_number": "25050",
  "road": "alessandro blvd",
  "unit": "ste b",
  "city": "moreno valley",
  "state": "ca",
  "postcode": "92553-4313"
}
```

Also notice that it's now trained on secondary units and can identify "Ste B" as such.

There's now an index of postal codes and their possible admin contexts, so something like 25050 would activate a variable in the model called "postcode no context" which essentially is there to disambiguate tokens that could be a postcode but have no supporting evidence in the form of city/state/country names the parser has seen with that postcode before. Over many examples the parser should learn a high negative weight for postcode and a high positive weight for house_number when this feature (attribute of the input) is present. There's also another feature called "postcode with context" that would be true if, say, 92553 were seen following "CA", "Moreno Valley", etc. In this case, over many examples, the parser learns the opposite i.e. high negative weights for house number and high positive weights for postcode.

Also we use a more powerful machine learning model, a Conditional Random Field, which can revise its previous decisions if it would help a subsequent token score higher. So even if it initially thinks "postcode", when it gets to the street name, instead of taking the previous tag as given, it's actually scoring over a matrix of all the possible tags the previous word could have taken on by all the tags the current word could take on. In this case, that might yield that the best label for "Alessandro" is "road" _and_ the best label for "25050" is now "house_number".

All that is to say that 1.0 is significantly better at disambiguating between postal codes and house numbers in the US and around the world.
