### ISSUE TITLE
Remove scripts/setup.py

### ISSUE THREAD

**Issue by steveha-ziprecruiter** [openvenues/libpostal#54]
Since the Python bindings now have their own repo, and since `scripts/setup.py` did not work when I tried it, I suggest removing `scripts/setup.py` from this repo.

Note: When I was trying to figure out how to install the Python bindings, Google found issue #10 and I tried the process described there.  I should have just started with the `README.md` file!  (I edited issue #10 to help out anyone who does the same thing I did.)

**Comment by thatdatabaseguy** [comment]
Hey Steve - the setup.py in ```scripts``` is not related to the Python bindings.

The ```scripts``` directory contains many of the supporting scripts (mostly Python) for preprocessing the various open geo data sets required to build/train the models in libpostal. It shouldn't be needed by most users of the C library, but is actively used during training.

Thanks for updating the old issue. It was from before libpostal was made public and much has changed since then.
