### ISSUE TITLE
French for 20 seems incorrect

### ISSUE THREAD

**Issue by steveha-ziprecruiter** [openvenues/libpostal#56]
Address expansion should rewrite words to numbers.  Testing with the command-line tool `src/libpostal`, it fails with this correct French address:

`src/libpostal 'Quatre-vingt-douze Ave des Champs-Élysées'`

Result:
```
12 avenue des champs-elysees
12 avenue des champs elysees
12 avenue des champselysees
42012 avenue des champs-elysees
42012 avenue des champs elysees
42012 avenue des champselysees
```

However, if you misspell "vingt" by swapping the 'g' and the 'n' it works as expected:

`src/libpostal 'Quatre-vignt-douze Ave des Champs-Élysées'`

Result:
```
92 avenue des champs-elysees
92 avenue des champs elysees
92 avenue des champselysees
```

I'm not a native French speaker so I verified the correct spelling of "vingt":

http://dictionary.reverso.net/french-english/vingt

If you enter `vignt` into the search box on the reverso.net site, it corrects it to `vingt` and displays the same URL as the one quoted above.

Note: this example came from the blog posting announcing `libpostal`.  I shared the blog posting and one of my co-workers spotted the misspelling, so I don't get the credit for spotting this.

**Comment by thatdatabaseguy** [comment]
:open_mouth: never noticed that (strangely no French speakers pointed it out yet either). Thanks! It has been fixed in libpostal and the example is being updated across the bindings.

Just pull latest from libpostal (this repo), then run ```make clean``` followed by ```make``` and ```sudo make install```.  For the Python bindings, I would also run ```pip uninstall postal``` followed by ```pip install postal``` for good measure to make sure it recompiles the Python bindings.
