### ISSUE TITLE
Request to be added as maintainer

### ISSUE THREAD

**Issue by NickCrews** [openvenues/libpostal#655]
Hi! I would love to
- go through and merge the obvious, easy PRs that are open
- close/deal with easy issues
- add a GitHub bot that tags a release every week/month. This would allow people to have a recent version to build against that is still stable. Also would allow for an official homebrew formula to ease installation.

Can you give me permissions to be able to do this? Appreciate it!

**Comment by NickCrews** [comment]
@albarrentine @missinglink

**Comment by missinglink** [comment]
Sounds good to me, my basic knowledge of C has prevented me from handling much other than administrative duties.

**Comment by albarrentine** [comment]
@NickCrews sounds good. I just reverted a few changes the Senzing team had been making recently without pull requests and spoke to them about it offline, so removed the last version tag, don't think that affects any of the existing PRs.

Would love to get some of the issues/PRs resolved. If it's minor, ok to merge, but not anything for now that changes the API.

Re: builds, only thing I'd caution for the moment is around rebuilding data files. Since the parser and e.g. the abbreviations dictionary are not entirely independent, the data files are no longer built automatically on merge as was once the case because it might require parser retraining, which is quite involved. That means technically we should be able to merge most of the abbreviations, etc. that folks contributed it just may not have an impact on results at present. I am experimenting in https://github.com/goodcleanfun with reworking the C codebase into modular, independent components that use clib (which is like copy/paste, not a huge clunky package manager or dependency nightmare, no corporate megacode), making them suitable for other areas of NLP/ML. The transparency level in that world of late leaves much to be desired so I am, quietly, building out some ideas which will find their way back into libpostal.

On things like duckdb integrations and what not, I'm opting not to proceed with the ideas that have been suggested so far around thread-safety, etc. Have something else entirely in mind around model storage that renders some of it moot.

**Comment by NickCrews** [comment]
roger, I must admit I don't really want the responsibility of in-depth changes, so limiting myself to minor fixups sounds great :)

**Comment by albarrentine** [comment]
Awesome, should be added, and many thanks!
