### ISSUE TITLE
Training form or script after tokenization

### ISSUE THREAD

**Issue by tdicken73** [openvenues/libpostal#67]
I have addresses in this form as noted in #1 
`123/house_number Main/road Street/road New/city York/city New/state York/state 10003/postcode`
It was said that, "the source text should be tokenized using libpostal's tokenizer (since that's what will be used at runtime). " However, when using the tokenizer.py in geodata.text, the results come back as WORD, NUMERIC, or COMMA, as seen below.
<img width="1042" alt="screen shot 2016-06-03 at 4 24 13 pm" src="https://cloud.githubusercontent.com/assets/6421218/15793144/a967962c-29a7-11e6-874c-4c55fef56116.png">
From the tokenizer within geodata.text, I'm able to see the tokenization of the data. What part of libpostal beyond the tokenizer is needed to be able to train it on our data? If the data is already in this form: `123/house_number Main/road Street/road New/city York/city New/state York/state 10003/postcode`, is there a way or a script I may be missing to pass it to the training model for training in this state as it is?

**Comment by thatdatabaseguy** [comment]
I've thought about the general idea some more and while it's technically possible, I don't want to encourage training libpostal on proprietary data sets. The goal of making the OSM training process open-source was for researchers, etc. to be able to replicate that training process, not to build a general BYO data address learning system. That may eventually be possible, but is not a current priority.

The models in libpostal are designed to learn over massive data sets, and (correct me if this is mistaken) I'll assume we're talking several orders of magnitude fewer examples than the 50-100 million in a data set like OSM or OpenAddresses. Training on 50 million examples and training on 50 thousand are different problems because of e.g. sparsity of place names (with OSM we can basically ensure that every possible city, neighborhood, suburb, etc. is in the training data and keep a dictionary of those names to help with parsing), as well as speed/scalability of the learning algorithm.

In practice, I'd guess most of the addresses in your database are going to be in OSM already (or there are similar addresses on the same street, etc.) and have been incorporated into the global model.

Possibly of interest: there's a new model being developed in the [parser-data](https://github.com/openvenues/libpostal/tree/parser-data) branch which is leaps and bounds better than what's in master, fixes most of the parsing issues people have brought up and many more, and includes several new tags like PO box, unit, etc. That's worth checking out when the release is ready.

Alternatively, if it's still necessary to train on your own data, and your addresses are only in the US, and Python-only is ok, I would recommend checking out [usaddress](https://github.com/datamade/usaddress), which is designed to be trained on user CSVs and the like. That project uses a slower-to-train but slightly more accurate model that should fare better with a relatively small number of training examples.
