### ISSUE TITLE
Indian Address Support

### ISSUE THREAD

**Issue by mohitgoyal201617** [openvenues/libpostal#68]
Hi,

Just want know "does libpostal support Indian Addresses". If no then how can i add support for those.

**Comment by thatdatabaseguy** [comment]
Yes it does. The currently-deployed parser is trained on about 30,000 addresses in India across most states (the first version only considered addresses with both a house number and a road name in OpenStreetMap).

That said, even in my limited experience navigating around New Delhi, I'm wary of making blanket statements about being able to handle Indian addresses :-).

Urban addresses and more populous states like Uttar Pradesh are better-represented in OSM so I'm sure there are some addresses or place names the parser will get wrong simply because it hasn't seen them before.

There's a new parser model being developed in the [parser-data](https://github.com/openvenues/libpostal/tree/parser-data) branch which trains on significantly more data and has at last count trains on > 120k examples in India and it should be possible to get more out of OSM by creating training examples for simple place names as well as road + place name. The new version also is able to parse a good deal of sub-building information like "Flat 3", "1st Floor", "Staircase B", in addition to PO boxes, etc. I've done some light testing of Indian addresses and place names using that model and it looks good so far.

If you have some addresses that you're able to contribute to [OpenStreetMap](https://openstreetmap.org), libpostal can import them from there.

**Comment by thatdatabaseguy** [comment]
The parser-data model has now been merged into master, and should do reasonably well on Indian addresses, with the exception of some landmarks or complicated direction-based addresses. Let me know if there are any specific issues.
