### ISSUE TITLE
Any mirror for downloading libpostal data file?

### ISSUE THREAD

**Issue by hieudt** [openvenues/libpostal#74]
I'm trying to install libpostal on my mac but the download speed for the command `libpostal_data download all` is extremely slow, under 1 KB/s, it takes forever to run, sometimes the connection is suddenly dropped though my internet is still good.

Could anyone make a mirror for these data files please?

**Comment by thatdatabaseguy** [comment]
Hey Hieu - let me know if this works:

I've created some new S3 buckets hosted in AWS's Asia-Pacific region, specifically ap-southeast-1 (Singapore, probably the closest data center to you) and ap-northeast-1 (Tokyo) and uploaded the model files to each.

Try changing this line in [src/libpostal_data](https://github.com/openvenues/libpostal/tree/master/src/libpostal_data)

```shell
LIBPOSTAL_S3_BUCKET_NAME="libpostal"
```

to:
```shell
LIBPOSTAL_S3_BUCKET_NAME="libpostal-ap-southeast-1"
```

and running ```make``` again.

That should be much faster than sending 2G of files from the US East data center in Virginia. If that works, we'll modify the DNS and that script to use a latency-based routing policy to select the closest server whenever that script is run in the future.

**Comment by hieudt** [comment]
Thanks for creating new S3 buckets in Asia Pacific but it does not help much for me, the download speed is still slow :(

**Comment by thatdatabaseguy** [comment]
Hm, still under 1Kb/s? If regular Internet works fine (this should take about as long as downloading a 1-hour TV show), it might either have to do with connections from your machine to S3 or perhaps international connections. I'm not an expert, but the two things I would probably try are:

1. Test download speed from Singapore generally with something like http://www.speedtest.com.sg/
2. Try downloading a different file from S3 and see if it's equally slow. One example of something relatively large is this OSM extract from Mapzen, also hosted on S3: https://s3.amazonaws.com/metro-extracts.mapzen.com/tokyo_japan.osm.pbf

If either of those is slow, you might want to try compiling on an external server. If you use AWS, spinning up an EC2 machine/spot instance and compiling from there will guarantee a very fast connection to S3.

**Comment by hieudt** [comment]
Thanks for the suggestions but I managed to download the tar files using JDownloader, it took 5 hrs to download them all then I untar them to $LIBPOSTAL_DATA_DIR and run make again. Now I can run `./src/address_parser` and it works perfectly.

**Comment by thatdatabaseguy** [comment]
Huzzah! Sometimes more workers/threads/connections can have an impact on large S3 downloads, which may be why JDownloader saw higher throughput than parallel curl with the default 5 workers.

I've made a few changes to the download script to mimic aws cli (what most people use for S3 downloads, though I didn't want to make it a dependency for installing libpostal). It downloads 64M chunks instead of size/num_workers chunks, and uses a process pool of 10 workers by default, which can be adjusted as necessary but seems to be the default used in most S3 multipart downloaders. The libpostal_data script now uses those same defaults, which should hopefully make downloads a bit faster.
